Repository NuGet/NuGet.Client, pull requests merged in 2020-10, with the labels that each got.

#3677 Use BitmapCreateOptions.IgnoreColorProfile to workaround WPF issue when using DecodePixelWidth
  src/NuGet.Clients/NuGet.PackageManagement.UI/Converters/IconUrlToImageCacheConverter.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/Converters/IconUrlToImageCacheConverterTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/NuGet.PackageManagement.UI.Test.csproj
  test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/Resources/grayicc.png
Labels: Approved for CI, Community

#3644 Enable custom CPS projects to be restored
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/GlobalSuppressions.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/IDE/VSSolutionManager.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.csproj
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/CpsPackageReferenceProject.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/CpsPackageReferenceProjectProvider.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/LegacyPackageReferenceProjectProvider.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/NuGetProjectFactory.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Telemetry/VSTelemetryServiceUtility.cs
  src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreJob.cs
  src/NuGet.Clients/NuGet.VisualStudio.Common/IDE/VsHierarchyUtility.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstaller.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/NetCorePackageReferenceProjectTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Services/NuGetProjectManagerServiceTests.cs
Labels: Approved for CI, Community

#3637 Improve test fixtures and related code
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/Util.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetToolTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/MsbuildIntegrationTestFixture.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/PackCommandTests.cs
  test/NuGet.Core.FuncTests/Msbuild.Integration.Test/MsbuildIntegrationTestFixture.cs
  test/NuGet.Core.FuncTests/Msbuild.Integration.Test/MsbuildRestoreTaskTests.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/NETCoreRestoreTestUtility.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/NETCoreRestoreTestUtility.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/RestoreBuildTargetsAndPropsTests.cs
  test/TestUtilities/Test.Utility/SimpleTestSetup/SimpleTestProjectContext.cs
  test/TestUtilities/Test.Utility/TestDirectory.cs
Labels: Approved for CI, Community

#3696 Fix broken links in debugging documentation
  docs/debugging.md
Labels: Approved for CI, Community

#3697 Fix broken link to Windows 10 SDK
  CONTRIBUTING.md
Labels: Approved for CI, Community

#3717 correctly suppress aliased dependencies according to request
  src/NuGet.Core/NuGet.Build.Tasks.Pack/PackTaskLogic.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/PackCommandTests.cs
Labels: servicing-consider

#3270 Fix output path issues with customized builds
  src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPackCommandTest.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/PackCommandTests.cs
Labels: Approved for CI, Community

#3691 error when missing tpv and platform present
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
  src/NuGet.Core/NuGet.Commands/Strings.Designer.cs
  src/NuGet.Core/NuGet.Commands/Strings.resx
  src/NuGet.Core/NuGet.Common/Errors/NuGetLogCode.cs
  src/NuGet.Core/NuGet.Common/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Common/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Common/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs
  src/NuGet.Core/NuGet.Packaging/Strings.Designer.cs
  src/NuGet.Core/NuGet.Packaging/Strings.resx
  test/NuGet.Core.FuncTests/NuGet.Commands.FuncTest/RestoreCommandTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/PackageBuilderTest.cs
Labels: servicing-consider

#3720 Updated the license list to bring in MIT-0 OSI approval
  src/NuGet.Core/NuGet.Packaging/Licenses/NuGetLicenseData.cs
Labels: Approved for CI

#3723 Fix InternalsVisibleTo for unsigned builds
  src/NuGet.Core/NuGet.LibraryModel/AssemblyInfo.cs
Labels: Approved for CI, Community

#3731 Use V3 for DncEng BAR publishing
  NuGet.Config
  build/bootstrap.proj
  build/common.project.props
  build/publish.proj
  build/templates/Build_and_UnitTest.yml
Labels: Approved for CI, Community
