Repository NuGet/NuGet.Client, pull requests merged in 2022-03, with the labels that each got.

#4483 Remove unneeded allocations parsing assets file
  src/NuGet.Core/NuGet.ProjectModel/JsonUtility.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileFormat.cs
Labels: Approved for CI

#4025 Add option to override transitive dependency versions when managing packages centrally
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/LegacyPackageReferenceProject.cs
  src/NuGet.Clients/NuGet.SolutionRestoreManager/VSNominationUtilities.cs
  src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
  src/NuGet.Core/NuGet.Build.Tasks.Console/MSBuildStaticGraphRestore.cs
  src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/MSBuildRestoreUtility.cs
  src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectBuildProperties.cs
  src/NuGet.Core/NuGet.PackageManagement/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs
  src/NuGet.Core/NuGet.ProjectModel/PackageSpecReferenceDependencyProvider.cs
  src/NuGet.Core/NuGet.ProjectModel/PackageSpecWriter.cs
  src/NuGet.Core/NuGet.ProjectModel/ProjectRestoreMetadata.cs
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Unshipped.txt
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/ProjectSystems/LegacyPackageReferenceProjectTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/ProjectSystems/TestVSProjectAdapter.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsSolutionRestoreServiceTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/PackCommandTests.cs
  test/NuGet.Core.Tests/NuGet.Build.Tasks.Console.Test/MSBuildStaticGraphRestoreTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/MSBuildRestoreUtilityTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/RestoreCommandTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/RestoreRunnerTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/PackageSpecReferenceDependencyProviderTests.cs
  test/TestUtilities/Test.Utility/Commands/ProjectTestHelpers.cs
Labels: Approved for CI, Community

#4488 Do not delete `ilmerge\NuGet.Build.Tasks.Pack.dll` when running integration tests
  test/TestUtilities/Test.Utility/TestDotnetCLiUtility.cs
Labels: Approved for CI, Community

#4404 Apply source-build patches
  build/common.project.props
  build/common.targets
  build/packages.targets
  src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj
  src/NuGet.Core/NuGet.CommandLine.XPlat/NuGet.CommandLine.XPlat.csproj
  src/NuGet.Core/NuGet.Common/NuGet.Common.csproj
  src/NuGet.Core/NuGet.Configuration/NuGet.Configuration.csproj
  src/NuGet.Core/NuGet.Frameworks/NuGet.Frameworks.csproj
  src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj
  src/NuGet.Core/NuGet.Packaging.Extraction/NuGet.Packaging.Extraction.csproj
  src/NuGet.Core/NuGet.Protocol/HttpSource/HttpRequestMessageExtensions.cs
  src/NuGet.Core/NuGet.Protocol/HttpSource/HttpRetryHandler.cs
  src/NuGet.Core/NuGet.Protocol/HttpSource/HttpSourceAuthenticationHandler.cs
  src/NuGet.Core/NuGet.Versioning/NuGet.Versioning.csproj
Labels: Approved for CI, Community

#4504 Use ProjectInstance.FromFile instead of Project.FromFile + Project.CreateInstance
  src/NuGet.Core/NuGet.Build.Tasks.Console/MSBuildStaticGraphRestore.cs
Labels: Approved for CI, Community

#4222 Update .nupkg.metadata LastAccessedTime on restore
  src/NuGet.Core/NuGet.Commands/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netcoreapp5.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/DependencyGraphSpecRequestProvider.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommandProvidersCache.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreRequest.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/NoOpRestoreUtilities.cs
  src/NuGet.Core/NuGet.Commands/Strings.Designer.cs
  src/NuGet.Core/NuGet.Commands/Strings.resx
  src/NuGet.Core/NuGet.Common/Errors/NuGetLogCode.cs
  src/NuGet.Core/NuGet.Common/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Common/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Common/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Configuration/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Configuration/Utility/ConfigurationContants.cs
  src/NuGet.Core/NuGet.Configuration/Utility/SettingsUtility.cs
  src/NuGet.Core/NuGet.Protocol/PackagesFolder/LocalPackageFileCache.cs
  src/NuGet.Core/NuGet.Protocol/PackagesFolder/NuGetv3LocalRepository.cs
  src/NuGet.Core/NuGet.Protocol/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Protocol/PublicAPI/netcoreapp5.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Protocol/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetRestoreTests.cs
  test/NuGet.Core.FuncTests/NuGet.Commands.FuncTest/RestoreCommandTests.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/InstallPackagesTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/InstallPackagesTests.cs
  test/NuGet.Core.Tests/NuGet.Configuration.Test/SettingsUtilityTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/LocalPackageFileCacheTests.cs
Labels: Approved for CI, Community

#4511 Add support for the NUGET_SCRATCH environment variable.
  src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs
Labels: Approved for CI, Community

#4525 Cache assets file in the project context
  test/TestUtilities/Test.Utility/SimpleTestSetup/SimpleTestProjectContext.cs
Labels: Merge next release

#4516 Remove duplicate and unused loc resources
  src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/Resources.Designer.cs
  src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/Resources.resx
  src/NuGet.Clients/NuGet.PackageManagement.UI/Resources.Designer.cs
  src/NuGet.Clients/NuGet.PackageManagement.UI/Resources.resx
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Strings.Designer.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Strings.resx
  src/NuGet.Clients/NuGet.SolutionRestoreManager/Resources.Designer.cs
  src/NuGet.Clients/NuGet.SolutionRestoreManager/Resources.resx
  src/NuGet.Clients/NuGet.Tools/Resources.Designer.cs
  src/NuGet.Clients/NuGet.Tools/Resources.resx
  src/NuGet.Clients/NuGet.VisualStudio.Common/Resources.Designer.cs
  src/NuGet.Clients/NuGet.VisualStudio.Common/Resources.resx
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/Resources/VsResources.Designer.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/Resources/VsResources.resx
  src/NuGet.Clients/NuGet.VisualStudio.OnlineEnvironment.Client/Resources.Designer.cs
  src/NuGet.Clients/NuGet.VisualStudio.OnlineEnvironment.Client/Resources.resx
  src/NuGet.Clients/NuGetConsole.Host.PowerShell/Common/CommonResources.Designer.cs
  src/NuGet.Clients/NuGetConsole.Host.PowerShell/Common/CommonResources.resx
  src/NuGet.Clients/NuGetConsole.Host.PowerShell/NuGetConsole.Host.PowerShell.csproj
  src/NuGet.Clients/NuGetConsole.Host.PowerShell/Resources.Designer.cs
  src/NuGet.Clients/NuGetConsole.Host.PowerShell/Resources.resx
  src/NuGet.Core/NuGet.CommandLine.XPlat/Strings.Designer.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Strings.resx
  src/NuGet.Core/NuGet.Commands/Strings.Designer.cs
  src/NuGet.Core/NuGet.Commands/Strings.resx
  src/NuGet.Core/NuGet.Common/Strings.Designer.cs
  src/NuGet.Core/NuGet.Common/Strings.resx
  src/NuGet.Core/NuGet.Configuration/Resources.Designer.cs
  src/NuGet.Core/NuGet.Configuration/Resources.resx
  src/NuGet.Core/NuGet.Credentials/Resources.Designer.cs
  src/NuGet.Core/NuGet.Credentials/Resources.resx
  src/NuGet.Core/NuGet.Frameworks/Strings.Designer.cs
  src/NuGet.Core/NuGet.Frameworks/Strings.resx
  src/NuGet.Core/NuGet.PackageManagement/Strings.Designer.cs
  src/NuGet.Core/NuGet.PackageManagement/Strings.resx
  src/NuGet.Core/NuGet.Packaging/Strings.Designer.cs
  src/NuGet.Core/NuGet.Packaging/Strings.resx
  src/NuGet.Core/NuGet.ProjectModel/Strings.Designer.cs
  src/NuGet.Core/NuGet.ProjectModel/Strings.resx
  src/NuGet.Core/NuGet.Protocol/Strings.Designer.cs
  src/NuGet.Core/NuGet.Protocol/Strings.resx
  src/NuGet.Core/NuGet.Resolver/Strings.Designer.cs
  src/NuGet.Core/NuGet.Resolver/Strings.resx
Labels: Merge next release

#4524 Create a dummy target for every tfm/rid combo when a project being restored is inconsistent in locked mode
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
  src/NuGet.Core/NuGet.Commands/Utility/RequestRuntimeUtility.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/RestoreCommandTests.cs
Labels: Merge next release

#4484 Check for duplicate NuGet items, and raise warnings/errors where appropriate
  src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs
  src/NuGet.Core/NuGet.Build.Tasks/CheckForDuplicateNuGetItemsTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GlobalSuppressions.cs
  src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets
  src/NuGet.Core/NuGet.Build.Tasks/Strings.Designer.cs
  src/NuGet.Core/NuGet.Build.Tasks/Strings.resx
  src/NuGet.Core/NuGet.Common/Errors/NuGetLogCode.cs
  src/NuGet.Core/NuGet.Common/PublicAPI/net45/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Common/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Common/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetRestoreTests.cs
  test/NuGet.Core.Tests/NuGet.Build.Tasks.Test/CheckForDuplicateNuGetItemsTaskTests.cs
Labels: Merge next release

#4515 Remove PackageRestoreTest.ps1 E2E tests
  NuGet.sln
  build/NuGet-WithApex.sln
  eng/pipelines/templates/pipeline.yml
  scripts/e2etests/Utils.ps1
  test/EndToEnd/NuGet.Tests.psm1
  test/EndToEnd/tests/InstallPackageTest.ps1
  test/EndToEnd/tests/PackageRestoreTest.ps1
  test/EndToEnd/tests/UninstallPackageTest.ps1
  test/EndToEnd/tests/UpdatePackageTest.ps1
Labels: Merge next release

#4514 fetch MsBuild version from -MsBuildPath option if it is passed to nuget.exe restore command
  src/NuGet.Clients/NuGet.CommandLine/MsBuildToolset.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/MsBuildToolsetTest.cs
Labels: Merge next release
