Repository NuGet/NuGet.Client, pull requests merged in 2023-04, with the labels that each got.

#5097 Add nullable annotations to NuGet.Versioning and tests
  build/Shared/HashCodeCombiner.cs
  build/Shared/NullableAttributes.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/NullableAnnotations.cs
  src/NuGet.Clients/NuGet.VisualStudio.Internal.Contracts/Formatters/FloatRangeFormatter.cs
  src/NuGet.Clients/NuGet.VisualStudio.Internal.Contracts/Formatters/IPackageReferenceContextInfoFormatter.cs
  src/NuGet.Clients/NuGet.VisualStudio.Internal.Contracts/Formatters/ITransitivePackageReferenceContextInfoFormatter.cs
  src/NuGet.Clients/NuGet.VisualStudio.Internal.Contracts/Formatters/NuGetVersionFormatter.cs
  src/NuGet.Core/NuGet.Versioning/FloatRange.cs
  src/NuGet.Core/NuGet.Versioning/GlobalSuppressions.cs
  src/NuGet.Core/NuGet.Versioning/NuGet.Versioning.csproj
  src/NuGet.Core/NuGet.Versioning/NuGetVersion.cs
  src/NuGet.Core/NuGet.Versioning/NuGetVersionFactory.cs
  src/NuGet.Core/NuGet.Versioning/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Versioning/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Versioning/Resources.Designer.cs
  src/NuGet.Core/NuGet.Versioning/Resources.resx
  src/NuGet.Core/NuGet.Versioning/ResourcesFormatter.cs
  src/NuGet.Core/NuGet.Versioning/SemanticVersion.cs
  src/NuGet.Core/NuGet.Versioning/SemanticVersionBase.cs
  src/NuGet.Core/NuGet.Versioning/SemanticVersionConverter.cs
  src/NuGet.Core/NuGet.Versioning/SemanticVersionFactory.cs
  src/NuGet.Core/NuGet.Versioning/VersionComparer.cs
  src/NuGet.Core/NuGet.Versioning/VersionExtensions.cs
  src/NuGet.Core/NuGet.Versioning/VersionFormatter.cs
  src/NuGet.Core/NuGet.Versioning/VersionRange.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeBase.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeComparer.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeFactory.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeFormatter.cs
  test/NuGet.Clients.Tests/NuGet.VisualStudio.Internal.Contracts.Test/Formatters/FloatRangeFormatterTests.cs
  test/NuGet.Clients.Tests/NuGet.VisualStudio.Internal.Contracts.Test/Formatters/VersionRangeFormatterTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/Converters/VersionRangeConverterTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/ExampleComparers.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/FloatingRangeTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/NuGet.Versioning.Test.csproj
  test/NuGet.Core.Tests/NuGet.Versioning.Test/NuGetVersionTest.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/SemVer201SpecTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/SemanticVersionConverterTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/SemanticVersionTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/VersionExtensionsTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/VersionParsingTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/VersionRangeComparerTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/VersionRangeFloatParsingTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/VersionRangeTests.cs
Labels: Merge next release

#5107 Add missing RegistrationsBaseUrls to prevent exceptions when loading valid Service Indexes.
  src/NuGet.Core/NuGet.Protocol/Providers/RegistrationResourceV3Provider.cs
  src/NuGet.Core/NuGet.Protocol/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Protocol/PublicAPI/netcoreapp5.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Protocol/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Protocol/ServiceTypes.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/Resources/RegistrationResourceV3ProviderTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/ServiceTypesTests.cs
Labels: Approved for CI, Community

#5125 Add RollForward to NuGet.Build.Tasks.Console
  src/NuGet.Core/NuGet.Build.Tasks.Console/NuGet.Build.Tasks.Console.csproj
Labels: Approved for CI, Community

#5102 Add two test cases for updating all packages in PMC
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetConsoleTestCase.cs
Labels: Approved for CI

#5127 Avoid boxing enum
  src/NuGet.Core/NuGet.LibraryModel/LibraryRange.cs
Labels: Approved for CI

#5114 Add Apex test case for IOS project to install/update/uninstall package
  .vsconfig
  build/tests.dev17.vsconfig
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetConsoleTestCase.cs
Labels: Approved for CI

#5132 Remove MinimalTargetFrameworksExeSigning from MinimalTargetFrameworksExeSigning in source-build
  build/common.project.props
Labels: Approved for CI, Community

#5122 Fall back to using API key also for pushing symbol packages if nothing else was specified as parameter or config
  src/NuGet.Core/NuGet.Commands/CommandRunners/PushRunner.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPushCommandTest.cs
Labels: Approved for CI, Community
