Repository NuGet/NuGet.Client, pull requests merged in 2023-11, with the labels that each got.

#5442 Fix tests failing when run on systems with non-English language/locale settings
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/CpsPackageReferenceProjectTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Services/NuGetPackageFileServiceTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Services/NuGetProjectManagerServiceTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Services/NuGetSourcesServiceTests.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/SolutionUpToDateCheckerTests.cs
  test/NuGet.Clients.Tests/NuGet.Tools.Test/NuGetBrokeredServiceFactoryTests.cs
  test/NuGet.Core.Tests/NuGet.Common.Test/CryptoHashProviderTest.cs
  test/NuGet.Core.Tests/NuGet.Common.Test/DateTimeUtilityTests.cs
  test/NuGet.Core.Tests/NuGet.Configuration.Test/SearchTreeTest.cs
  test/NuGet.Core.Tests/NuGet.Configuration.Test/SettingsTests.cs
  test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/GraphNodeTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/ManifestTest.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/JsonPackageSpecReaderTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/JsonTextReaderExtensionsTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/Resources/PackageUpdateResourceTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/NuGet.Versioning.Test.csproj
  test/NuGet.Core.Tests/NuGet.Versioning.Test/NuGetVersionTest.cs
  test/TestUtilities/Test.Utility/PlatformXunitAttributes/UseCultureAttribute.cs
Labels: Approved for CI, Community

#5496 Eliminate obsolete API warnings/errors in product source-build
  src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/Exceptions/PackageSourceException.cs
  src/NuGet.Core/NuGet.Commands/Common/CommandException.cs
  src/NuGet.Core/NuGet.Configuration/Exceptions/NuGetConfigurationException.cs
  src/NuGet.Core/NuGet.Frameworks/FrameworkException.cs
  src/NuGet.Core/NuGet.Packaging/Licenses/NuGetLicenseExpressionParsingException.cs
  src/NuGet.Core/NuGet.Protocol/Exceptions/FatalProtocolException.cs
  src/NuGet.Core/NuGet.Protocol/Exceptions/InvalidCacheProtocolException.cs
  src/NuGet.Core/NuGet.Protocol/Exceptions/NuGetProtocolException.cs
  src/NuGet.Core/NuGet.Protocol/Exceptions/RetriableProtocolException.cs
  src/NuGet.Core/NuGet.Protocol/Plugins/PluginException.cs
  src/NuGet.Core/NuGet.Protocol/Plugins/ProtocolException.cs
  src/NuGet.Core/NuGet.Resolver/Exceptions/NuGetResolverConstraintException.cs
  src/NuGet.Core/NuGet.Resolver/Exceptions/NuGetResolverException.cs
  src/NuGet.Core/NuGet.Resolver/Exceptions/NuGetResolverInputException.cs
Labels: Approved for CI, Community

#5498 Don't log task inputs and outputs when binary logger is enabled
  src/NuGet.Core/NuGet.Build.Tasks/BuildTasksUtility.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetCentralPackageVersionsTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetProjectTargetFrameworksTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetReferenceNearestTargetFrameworkTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetRestoreDotnetCliToolsTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetRestoreFrameworkReferencesTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetRestorePackageDownloadsTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetRestorePackageReferencesTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetRestoreProjectJsonPathTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetRestoreProjectReferencesTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetRestoreProjectStyleTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetRestoreSettingsTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GetRestoreSolutionProjectsTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/GlobalSuppressions.cs
  src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/WarnForInvalidProjectsTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/WriteRestoreGraphTask.cs
  test/NuGet.Core.Tests/NuGet.Build.Tasks.Test/GetReferenceNearestTargetFrameworkTaskTest.cs
  test/NuGet.Core.Tests/NuGet.Build.Tasks.Test/WarnForInvalidProjectsTaskTests.cs
Labels: Approved for CI, Community

#5497 Add responsive testing section in UI guidelines.
  docs/ui-guidelines.md
Labels: Status:No recent activity

#5510 Enable the ignored test cases since the related product bugs have been fixed
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetConsoleTestCase.cs
Labels: Approved for CI

#5511 Target net9.0 for .NET source build
  build/common.project.props
  build/common.targets
  eng/source-build/global.json
  src/NuGet.Core/NuGet.Configuration/NuGet.Configuration.csproj
  src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj
Labels: Approved for CI, Community

#5509 Add three apex tests for verify commonly used commands in PMC
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetConsoleTestCase.cs
Labels: Approved for CI
