Repository NuGet/NuGet.Client, pull requests merged in 2023-05, with the labels that each got.

#5021 Log warnings from server also when using an http proxy (X-NuGet-Warning)
  src/NuGet.Core/NuGet.Protocol/HttpSource/HttpHandlerResourceV3Provider.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/HttpHandlerResourceV3ProviderTests.cs
Labels: Approved for CI, Community

#5146 Show diagnostic beneath unresolved package/project reference in Solution Explorer
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/AssetsFileTopLevelDependenciesCollectionSourceProvider.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Items/PackageAssemblyItem.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Items/PackageBuildFileItem.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Items/PackageDocumentItem.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Items/PackageReferenceItem.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Models/AssetsFileDependenciesSnapshot.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Models/AssetsFileLibraryType.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Models/AssetsFileLogMessage.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Models/AssetsFileTarget.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Models/AssetsFileTargetLibrary.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/PackageReferenceAttachedCollectionSourceProvider.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/ProjectReferenceAttachedCollectionSourceProvider.cs
  test/NuGet.Clients.Tests/NuGet.VisualStudio.Implementation.Test/SolutionExplorer/Models/AssetsFileDependenciesSnapshotTests.cs
Labels: Approved for CI, Community

#5163 Add two Apex test cases to install latest package in PMC
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NetCoreProjectTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetConsoleTestCase.cs
Labels: Approved for CI

#5186 remove extra space
  eng/pipelines/templates/Build_and_UnitTest.yml
Labels: Community

#5187 fix syntax
  eng/pipelines/templates/Apex_Tests_On_Windows.yml
Labels: Community

#5188 use Join-Path to create path for build file
  eng/pipelines/templates/Apex_Tests_On_Windows.yml
Labels: Community

#5190 Enable source-build pre-built detection
  eng/SourceBuildPrebuiltBaseline.xml
  eng/source-build/build.sh
  eng/source-build/source-build.proj
Labels: Approved for CI, Community
