Repository NuGet/NuGet.Client, pull requests merged in 2023-06, with the labels that each got.

#5211 Update Build_and_UnitTest.yml
  eng/pipelines/templates/Apex_Tests_On_Windows.yml
  eng/pipelines/templates/Build_and_UnitTest.yml
  eng/pipelines/templates/pipeline.yml
Labels: Community

#5193 Target net8.0 for source-build
  build/common.project.props
  build/common.targets
  eng/source-build/global.json
  src/NuGet.Core/NuGet.Configuration/NuGet.Configuration.csproj
  src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj
Labels: Approved for CI, Community

#5207 Add dependencies for PVP flow
  Directory.Packages.props
  eng/Version.Details.xml
Labels: Approved for CI, Community

#5161 Add apex test -- Verify Init Scripts Execution
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetConsoleTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetUITestCase.cs
Labels: Approved for CI

#5205 Convert LibraryRangeCacheKey to a struct
  src/NuGet.Core/NuGet.DependencyResolver.Core/LibraryRangeCacheKey.cs
  src/NuGet.Core/NuGet.DependencyResolver.Core/PublicAPI.Unshipped.txt
Labels: Approved for CI, Perf, PublicAPI:ReviewNeeded

#5215 Add AsString() for LibraryDependencyTarget and LibraryIncludeFlags
  src/NuGet.Core/NuGet.LibraryModel/LibraryDependencyTargetUtils.cs
  src/NuGet.Core/NuGet.LibraryModel/LibraryIncludeFlagUtils.cs
  src/NuGet.Core/NuGet.LibraryModel/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.ProjectModel/PackageSpecWriter.cs
Labels: Approved for CI, Community

#5217 Ensure only one logging task is active at a time
  src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreOperationLogger.cs
Labels: Approved for CI, Community

#5199 Reduce allocations in TargetFrameworkInformation.Clone
  src/NuGet.Core/NuGet.ProjectModel/TargetFrameworkInformation.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/TargetFrameworkInformationTests.cs
Labels: Approved for CI, Community

#5201 Reduce allocations in PackageSpecReferenceDependencyProvider
  src/NuGet.Core/NuGet.ProjectModel/PackageSpecReferenceDependencyProvider.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/PackageSpecReferenceDependencyProviderTests.cs
Labels: Approved for CI, Community

#5206 Use default '/' split symbol in ETW events.
  src/NuGet.Clients/NuGet.VisualStudio.Common/Telemetry/EtwLogActivity.cs
Labels: Approved for CI, Community

#5228 Add System.Security.Cryptography.Xml dependency
  Directory.Packages.props
  eng/Version.Details.xml
Labels: Approved for CI, Community

#5197 Fix issue with solution filters not restoring when in different folder than referenced solution
  src/NuGet.Clients/NuGet.CommandLine/Common/ProjectInSolution.cs
  src/NuGet.Clients/NuGet.CommandLine/Common/Solution.cs
  src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetRestoreCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/Util.cs
Labels: Approved for CI, Community

#5227 Avoid string.Split allocations in LockFileFormat.ReadTargetLibrary
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileFormat.cs
Labels: Perf

#5226 Avoid allocating StringBuilder in some cases
  build/Shared/StringBuilderPool.cs
  src/NuGet.Core/NuGet.Common/PathUtil/PathUtility.cs
  src/NuGet.Core/NuGet.LibraryModel/LibraryRange.cs
  src/NuGet.Core/NuGet.Protocol/RemoteRepositories/HttpFileSystemBasedFindPackageByIdResource.cs
  src/NuGet.Core/NuGet.Versioning/FloatRange.cs
  src/NuGet.Core/NuGet.Versioning/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Versioning/VersionFormatter.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeFormatter.cs
Labels: Approved for CI, Perf

#5202 Avoid allocations while parsing NuGetVersion from strings
  src/NuGet.Core/NuGet.Versioning/NuGetVersionFactory.cs
Labels: Approved for CI, Community

#5200 Reduce allocations in ContentItemCollection
  src/NuGet.Core/NuGet.Packaging/ContentModel/ContentItemCollection.cs
  src/NuGet.Core/NuGet.Packaging/ContentModel/ContentItemGroup.cs
Labels: Approved for CI, Community

#5233 Add apex test -- Search Package in Browse/Installed/Updates tab from PMUI
  test/NuGet.Tests.Apex/NuGet.PackageManagement.UI.TestContract/ApexTestUIProject.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/Apex/NuGetUIProjectTestExtension.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetConsoleTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetUITestCase.cs
Labels: Approved for CI

#5196 add review comment to sb files
  eng/SourceBuild.props
  eng/SourceBuildPrebuiltBaseline.xml
Labels: Approved for CI, Community

#5251 Avoid dictionary lookups in loops
  build/Shared/DeconstructionExtensions.cs
  src/NuGet.Clients/NuGet.CommandLine/Commands/ProjectFactory.cs
  src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/Utils/InstalledPackageEnumerator.cs
  src/NuGet.Clients/NuGet.PackageManagement.UI/Options/PackageSourceMappingOptionsControl.xaml.cs
  src/NuGet.Clients/NuGet.VisualStudio.Common/Telemetry/ExtensibilityTelemetryCollector.cs
  src/NuGet.Clients/NuGet.VisualStudio.Common/Telemetry/PackageSourceTelemetry.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/Utility/DeconstructionExtensions.cs
  src/NuGet.Core/NuGet.Commands/MSBuildProjectFactory.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/ContentFiles/ContentFileUtils.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/TransitiveNoWarnUtils.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/MSBuildRestoreUtility.cs
  src/NuGet.Core/NuGet.PackageManagement/IDE/PackageRestoreManager.cs
  src/NuGet.Core/NuGet.PackageManagement/Resolution/ResolverGather.cs
  src/NuGet.Core/NuGet.PackageManagement/Utility/MSBuildNuGetProjectSystemUtility.cs
  src/NuGet.Core/NuGet.Packaging/NuspecReader.cs
  src/NuGet.Core/NuGet.Packaging/PackageReaderBase.cs
  src/NuGet.Core/NuGet.Resolver/ResolverInputSort.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NetworkCallCountTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreRetryTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetRestoreTests.cs
Labels: Perf

#5246 Enable non-allocating enumeration via collection interfaces
  build/Shared/NoAllocEnumerateExtensions.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/ContentFiles/ContentFileUtils.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs
  src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs
  src/NuGet.Core/NuGet.Packaging/Rules/InvalidUndottedFrameworkRule.cs
  test/NuGet.Core.Tests/NuGet.Common.Test/NoAllocEnumerateExtensionsTests.cs
Labels: Approved for CI, Perf

#5245 Specify SelectionCriteria list capacity correctly
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs
Labels: Approved for CI, Perf

#5261 Do less work in PackageSpecificWarningProperties classes
  src/NuGet.Core/NuGet.Commands/PackCommand/Logging/PackageSpecificWarningProperties.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/PackageSpecificWarningProperties.cs
Labels: Perf

#5244 Avoid allocating boxed List<T> enumerators
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/NoOpRestoreUtilities.cs
Labels: Approved for CI, Perf

#5276 fix crash on cancel in Restore task
  src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs
Labels: Approved for CI, Community

#5231 Create SingleFileProvider
  src/NuGet.Core/NuGet.Commands/RestoreCommand/ContentFiles/ContentFileUtils.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/ContentFiles/SingleFileProvider.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/ContentFiles/VirtualFileProvider.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/SingleFileProviderTests.cs
Labels: Approved for CI, Perf

#5249 Obsolete Clone methods on immutable types
  src/NuGet.Core/NuGet.Frameworks/FrameworkRuntimePair.cs
  src/NuGet.Core/NuGet.LibraryModel/DownloadDependency.cs
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/CompatibilityProfile.cs
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/RuntimeDependencySet.cs
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/RuntimeDescription.cs
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/RuntimeGraph.cs
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/RuntimePackageDependency.cs
  src/NuGet.Core/NuGet.ProjectModel/TargetFrameworkInformation.cs
  src/NuGet.Core/NuGet.Versioning/VersionRange.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeFactory.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/PackageSpecTests.cs
Labels: Perf

#5271 Remove allocations from PackageSource.Source setter
  src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSource.cs
Labels: Perf

#5252 Reduce allocations in ContentFileUtils.GetContentFileGroup
  src/NuGet.Core/NuGet.Commands/RestoreCommand/ContentFiles/ContentFileUtils.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/ContentFileUtilsTests.cs
Labels: Perf

#5269 Don't box enumerators in ContentItemCollection
  src/NuGet.Core/NuGet.Packaging/ContentModel/ContentItemCollection.cs
Labels: Perf

#5248 Reduce allocations in RuntimeDescription and RuntimeDependencySet
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/JsonRuntimeFormat.cs
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/RuntimeDependencySet.cs
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/RuntimeDescription.cs
  src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs
Labels: Perf

#5279 Reduce allocations in VersionRangeFormatter
  src/NuGet.Core/NuGet.Versioning/VersionFormatter.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeFormatter.cs
Labels: Perf
