Repository NuGet/NuGet.Client, pull requests merged in 2023-09, with the labels that each got.

#5403 OptProf test project should target latest SDK TFM
  test/NuGet.Tests.Apex/NuGet.OptProf/Assets/PackageReferenceSdk/PackageReferenceSdk/PackageReferenceSdk.csproj
Labels: Approved for CI

#5398 Stop warning NU1905 when NuGetAudit doesn't have vulnerability data to check
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/AuditUtility.cs
  src/NuGet.Core/NuGet.Common/Errors/NuGetLogCode.cs
  src/NuGet.Core/NuGet.Common/PublicAPI.Shipped.txt
  test/NuGet.Core.Tests/NuGet.Commands.Test/RestoreCommandTests/RestoreCommandTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/RestoreCommandTests/Utility/AuditUtilityTests.cs
Labels: Merge this release

#5406 Protocol to convert VulnerabilityInfoResource with System.Text.Json
  Directory.Packages.props
  build/common.project.props
  eng/SourceBuildPrebuiltBaseline.xml
  src/NuGet.Clients/NuGet.MSSigning.Extensions/ilmerge.props
  src/NuGet.Core/NuGet.Protocol/Converters/JsonExtensions.cs
  src/NuGet.Core/NuGet.Protocol/Converters/VersionRangeStjConverter.cs
  src/NuGet.Core/NuGet.Protocol/Model/PackageVulnerabilityInfo.cs
  src/NuGet.Core/NuGet.Protocol/Model/V3VulnerabilityIndexEntry.cs
  src/NuGet.Core/NuGet.Protocol/NuGet.Protocol.csproj
  src/NuGet.Core/NuGet.Protocol/Resources/VulnerabilityInfoResourceV3.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/Converters/VersionRangeStjConverterTests.cs
Labels: Merge this release

#5390 Do not warn http sources in package reference restore when allowInsecureConnections is set to true
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
  test/NuGet.Core.FuncTests/NuGet.Commands.FuncTest/RestoreCommandTests.cs
  test/TestUtilities/Test.Utility/Commands/TestRestoreRequest.cs
Labels: Merge this release

#5410 Run Dotnet.Integration.Tests with net8.0
  build/common.project.props
Labels: Merge this release

#5414 Remove unnecessary source-build patch
  eng/source-build-patches/0001-Rename-NuGet.Config-to-NuGet.config-to-account-for-a.patch
Labels: Approved for CI, Community, Merge this release

#5409 Add event tracing to NuGet.Common and write events for the NuGet-based MSBuid project SDK resolver
  src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/GlobalJsonReader.cs
  src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/NuGetSdkLogger.cs
  src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/NuGetSdkResolver.cs
  src/NuGet.Core/NuGet.Common/Migrations/MigrationRunner.cs
  src/NuGet.Core/NuGet.Common/NuGetEventSource.cs
  src/NuGet.Core/NuGet.Common/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Configuration/Settings/SettingsFile.cs
  src/NuGet.Core/NuGet.Configuration/Settings/SettingsLoadingContext.cs
Labels: Merge this release

#5418 Fix source-build CI regression
  eng/source-build/global.json
  eng/source-build/source-build.proj
Labels: Approved for CI, Community

#5372 make the method PatterExpression.Match internal
  src/NuGet.Core/NuGet.Packaging/ContentModel/Infrastructure/Parser.cs
  src/NuGet.Core/NuGet.Packaging/PublicAPI/net472/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netcoreapp5.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
Labels: Merge this release

#5419 Fix IPC error in Apex tests
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/IVsServicesTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NetCoreProjectTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetConsoleTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetPackageSigningTests/AuthorSignedPackageTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/xunit.runner.json
Labels: Merge this release

#5404 Vulnerabilities filter in PM UI
  src/NuGet.Clients/NuGet.PackageManagement.UI/Converters/PackageLevelGroupToBooleanConverter.cs
  src/NuGet.Clients/NuGet.PackageManagement.UI/Resources.Designer.cs
  src/NuGet.Clients/NuGet.PackageManagement.UI/Resources.resx
  src/NuGet.Clients/NuGet.PackageManagement.UI/ViewModels/PackageItemViewModel.cs
  src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/InfiniteScrollList.xaml
  src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/InfiniteScrollList.xaml.cs
  src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageManagerControl.xaml
  src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageManagerControl.xaml.cs
  src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageManagerTopPanel.xaml
  src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageManagerTopPanel.xaml.cs
Labels: Merge this release

#5416 Fix racing condition when stale a non-community PR
  .github/fabricbot.json
Labels: Merge this release

#5389 Add -NoHttpCache option and RestoreNoHttpCache property.
  src/NuGet.Clients/NuGet.CommandLine/Commands/DownloadCommandBase.cs
  src/NuGet.Clients/NuGet.CommandLine/Commands/HelpCommand.cs
  src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs
  src/NuGet.Clients/NuGet.CommandLine/Commands/OptionAttribute.cs
  src/NuGet.Clients/NuGet.CommandLine/Commands/RestoreCommand.cs
  src/NuGet.Clients/NuGet.CommandLine/NuGetCommand.Designer.cs
  src/NuGet.Clients/NuGet.CommandLine/NuGetCommand.resx
  src/NuGet.Clients/NuGet.CommandLine/Program.cs
  src/NuGet.Core/NuGet.Build.Tasks.Console/MSBuildStaticGraphRestore.cs
  src/NuGet.Core/NuGet.Build.Tasks/NuGet.RestoreEx.targets
  src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets
  src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/RestoreTaskEx.cs
  src/NuGet.Core/NuGet.Build.Tasks/Strings.Designer.cs
  src/NuGet.Core/NuGet.Build.Tasks/Strings.resx
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/CommandLineParserTests.cs
  test/NuGet.Core.Tests/NuGet.Build.Tasks.Test/RestoreTaskExTests.cs
Labels: Merge this release

#5417 Add nullable annotations to NuGet.LibraryModel
  NuGet.sln
  build/Shared/IsExternalInit.cs
  build/Shared/RequiredModifierAttributes.cs
  src/NuGet.Core/NuGet.LibraryModel/CentralPackageVersion.cs
  src/NuGet.Core/NuGet.LibraryModel/CentralPackageVersionNameComparer.cs
  src/NuGet.Core/NuGet.LibraryModel/DownloadDependency.cs
  src/NuGet.Core/NuGet.LibraryModel/FrameworkDependency.cs
  src/NuGet.Core/NuGet.LibraryModel/FrameworkDependencyFlagsUtils.cs
  src/NuGet.Core/NuGet.LibraryModel/Library.cs
  src/NuGet.Core/NuGet.LibraryModel/LibraryDependency.cs
  src/NuGet.Core/NuGet.LibraryModel/LibraryDependencyTargetUtils.cs
  src/NuGet.Core/NuGet.LibraryModel/LibraryExtensions.cs
  src/NuGet.Core/NuGet.LibraryModel/LibraryIdentity.cs
  src/NuGet.Core/NuGet.LibraryModel/LibraryIncludeFlagUtils.cs
  src/NuGet.Core/NuGet.LibraryModel/LibraryRange.cs
  src/NuGet.Core/NuGet.LibraryModel/LibraryType.cs
  src/NuGet.Core/NuGet.LibraryModel/NuGet.LibraryModel.csproj
  src/NuGet.Core/NuGet.LibraryModel/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.LibraryModel/PublicAPI.Unshipped.txt
  test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/LocalDependencyProviderTests.cs
  test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/RemoteDependencyWalkerTests.cs
  test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/ResolverFacts.cs
  test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/TrackerTests.cs
  test/NuGet.Core.Tests/NuGet.LibraryModel.Tests/FrameworkDependencyFlagsUtilsTests.cs
  test/NuGet.Core.Tests/NuGet.LibraryModel.Tests/FrameworkDependencyTests.cs
  test/NuGet.Core.Tests/NuGet.LibraryModel.Tests/LibraryDependencyTests.cs
  test/NuGet.Core.Tests/NuGet.LibraryModel.Tests/LibraryIncludeFlagUtilsTests.cs
  test/NuGet.Core.Tests/NuGet.LibraryModel.Tests/NuGet.LibraryModel.Tests.csproj
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/PackageSpecOperationsTests.cs
Labels: Merge next release
