Repository NuGet/NuGet.Client, pull requests merged in 2023-07, with the labels that each got.

#5259 Update .NET functional tests to make them more reliable
  build/build.proj
  eng/pipelines/templates/pipeline.yml
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Caching/NuGetExe/NuGetExe.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/CommandRunnerTest.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/InstallCommandTests.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/PushCommandTest.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/RestoreCommandSignPackagesTests.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/RestoreCommandTests.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/SearchCommandTests.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/SignCommandTests.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/TrustedSignersCommandTests.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/VerifyCommandTests.cs
  test/NuGet.Clients.FuncTests/NuGet.MSSigning.Extensions.FuncTest/Commands/MSSignCommandTests.cs
  test/NuGet.Clients.FuncTests/NuGet.MSSigning.Extensions.FuncTest/Commands/ReposignCommandTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/ExtensionsTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NetworkCallCountTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetAddCommandTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetClientCertCommandTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetConfigCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetDeleteCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetHelpCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetInitCommandTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetInstallCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetListCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetLocalsCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPackCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPushCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetRestoreCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetSetApiKeyTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetSourcesCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetSpecCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetUpdateCommandTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetVerifyCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/ProjectFactoryTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreProjectJsonTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreRetryTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreUAPPackageReferenceTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/Util.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetAddPackageTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetIntegrationCollection.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetIntegrationTestFixture.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetListPackageTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetRestoreTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetSignTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetSourcesTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetToolTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetTrustTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetVerifyTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/MsbuildIntegrationTestFixture.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/PackCommandTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/ProjectFileBuilder.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/ProjectPropertyTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/X509TrustStoreTests.cs
  test/NuGet.Core.FuncTests/Msbuild.Integration.Test/MsbuildIntegrationTestFixture.cs
  test/NuGet.Core.FuncTests/NuGet.Signing.CrossFramework.Test/CrossFrameworkVerificationTest.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatLocalsTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatTrustTests.cs
  test/TestUtilities/Test.Utility/CommandRunner.cs
  test/TestUtilities/Test.Utility/Signing/PlatformX509Store.cs
Labels: Merge next release

#5218 Reduce some allocations in CreateGraphNode.
  src/NuGet.Core/NuGet.DependencyResolver.Core/Remote/RemoteDependencyWalker.cs
  src/NuGet.Core/NuGet.Packaging/PackageCreation/Extensions/CollectionExtensions.cs
Labels: Approved for CI, Merge next release, Community

#5232 Reduce allocations in RuntimeGraph
  src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs
  src/NuGet.Core/NuGet.Packaging/PublicAPI/net472/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netcoreapp5.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/Rules/DependenciesGroupsForEachTFMRule.cs
  src/NuGet.Core/NuGet.Packaging/Rules/InvalidUndottedFrameworkRule.cs
  src/NuGet.Core/NuGet.Packaging/Rules/NoRefOrLibFolderInPackageRule.cs
  src/NuGet.Core/NuGet.Packaging/Rules/UpholdBuildConventionRule.cs
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/RuntimeGraph.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/DependenciesGroupsForEachTFMRuleTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/RuntimeModelTests/RuntimeGraphTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/JsonPackageSpecReaderTests.cs
Labels: Perf

#5293 DetectAndMarkAmbiguousCentralTransitiveDependencies should be exhaustive and deterministic
  src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/GraphOperations.cs
  test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/RemoteDependencyWalkerTests.cs
Labels: Approved for CI, Community

#5260 Don't allocate as many comparer instances
  src/NuGet.Clients/NuGet.CommandLine/Commands/RestoreCommand.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstallerServices.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageMetadataComparer.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/PreinstalledPackageInstaller.cs
  src/NuGet.Core/NuGet.Build.Tasks.Pack/PackTaskLogic.cs
  src/NuGet.Core/NuGet.Build.Tasks/BuildTasksUtility.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/AddPackageReferenceCommandRunner.cs
  src/NuGet.Core/NuGet.Commands/PackCommand/Logging/PackageSpecificWarningProperties.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/PackageSpecificWarningProperties.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/TransitiveNoWarnUtils.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/WarningPropertiesCollection.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/SpecValidationUtility.cs
  src/NuGet.Core/NuGet.Frameworks/CompatibilityProvider.cs
  src/NuGet.Core/NuGet.Frameworks/FrameworkNameProvider.cs
  src/NuGet.Core/NuGet.Frameworks/FrameworkRange.cs
  src/NuGet.Core/NuGet.Frameworks/FrameworkReducer.cs
  src/NuGet.Core/NuGet.Frameworks/NuGetFramework.cs
  src/NuGet.Core/NuGet.Frameworks/OneWayCompatibilityMappingEntry.cs
  src/NuGet.Core/NuGet.Frameworks/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Frameworks/comparers/CompatibilityMappingComparer.cs
  src/NuGet.Core/NuGet.Frameworks/comparers/FrameworkRangeComparer.cs
  src/NuGet.Core/NuGet.Frameworks/comparers/NuGetFrameworkFullComparer.cs
  src/NuGet.Core/NuGet.Frameworks/comparers/NuGetFrameworkNameComparer.cs
  src/NuGet.Core/NuGet.LibraryModel/CentralPackageVersionNameComparer.cs
  src/NuGet.Core/NuGet.PackageManagement/IDE/PackageRestoreManager.cs
  src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
  src/NuGet.Core/NuGet.PackageManagement/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.PackageManagement/Utility/MSBuildNuGetProjectSystemUtility.cs
  src/NuGet.Core/NuGet.PackageManagement/Utility/PackageReferenceComparer.cs
  src/NuGet.Core/NuGet.PackageManagement/Utility/SourceRepositoryComparer.cs
  src/NuGet.Core/NuGet.Packaging/Core/PackageIdentity.cs
  src/NuGet.Core/NuGet.Packaging/Core/comparers/PackageIdentityComparer.cs
  src/NuGet.Core/NuGet.Packaging/NuspecReader.cs
  src/NuGet.Core/NuGet.Packaging/PackageReaderBase.cs
  src/NuGet.Core/NuGet.Protocol/DependencyInfo/ResolverMetadataClient.cs
  src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedPackageInfo.cs
  src/NuGet.Core/NuGet.Protocol/Plugins/PluginPackageReader.cs
  src/NuGet.Core/NuGet.Protocol/ProviderComparer.cs
  src/NuGet.Core/NuGet.Protocol/SourceRepository.cs
  src/NuGet.Core/NuGet.Versioning/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Versioning/SemanticVersionBase.cs
  src/NuGet.Core/NuGet.Versioning/VersionComparer.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeBase.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeComparer.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeFactory.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsSolutionRestoreServiceTests.cs
  test/NuGet.Core.Tests/NuGet.Frameworks.Test/AssetTargetFallbackTests.cs
  test/NuGet.Core.Tests/NuGet.Frameworks.Test/DualCompatibilityFrameworkTests.cs
  test/NuGet.Core.Tests/NuGet.Frameworks.Test/FrameworkComparerTests.cs
  test/NuGet.Core.Tests/NuGet.Frameworks.Test/NuGetFrameworkTests.cs
  test/NuGet.Core.Tests/NuGet.PackageManagement.Test/PackageRestoreManagerTests.cs
  test/NuGet.Core.Tests/NuGet.PackageManagement.Test/Utility/PackageReferenceComparerTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/ExampleComparers.cs
Labels: Perf

#5267 Reduce allocations in NuGet.DependencyResolver.Tracker
  src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/Tracker.cs
  src/NuGet.Core/NuGet.DependencyResolver.Core/PublicAPI.Shipped.txt
  test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/TrackerTests.cs
Labels: Perf

#5278 Remove redundant SourceBuildTrimNetFrameworkTargets property
  eng/SourceBuild.props
Labels: Approved for CI, Community

#5283 [DartLab B2B feature] dropname for base VS should be retrieved using the baseline.
  eng/pipelines/templates/Apex_Tests_On_Windows.yml
  eng/pipelines/templates/End_To_End_Tests_On_Windows.yml
Labels: Approved for CI, Community

#5304 Improve hashing and equality allocations/performance
  build/Shared/EqualityUtility.cs
  build/Shared/HashCodeCombiner.cs
  build/Shared/NoAllocEnumerateExtensions.cs
  spelling.dic
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/PackageSearchMetadataCacheItem.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/TransitiveNoWarnUtils.cs
  src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSourceCredential.cs
  src/NuGet.Core/NuGet.Packaging/NupkgMetadata/NupkgMetadataFile.cs
  src/NuGet.Core/NuGet.Packaging/Signing/Verification/CertificateHashAllowListEntry.cs
  src/NuGet.Core/NuGet.Packaging/Signing/Verification/TrustedSignerAllowListEntry.cs
  src/NuGet.Core/NuGet.ProjectModel/ProjectRestoreMetadata.cs
  src/NuGet.Core/NuGet.ProjectModel/TargetFrameworkInformation.cs
  src/NuGet.Core/NuGet.ProjectModel/WarningProperties.cs
  test/NuGet.Core.Tests/NuGet.Common.Test/NoAllocEnumerateExtensionsTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/IncludeExcludeFilesTests.cs
  test/NuGet.Core.Tests/NuGet.Shared.Tests/HashCodeCombinerTests.cs
  test/NuGet.Core.Tests/NuGet.Versioning.Test/NuGet.Versioning.Test.csproj
Labels: Community, Perf

#5310 Reduce size of LockFileTargetLibrary
  NuGet.sln
  build/Shared/IsExternalInit.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Models/AssetsFileTargetLibrary.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileFormat.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileTargetLibrary.cs
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Unshipped.txt
Labels: Community, Perf

#5311 Null annotate PackageDependencyInfo
  spelling.dic
  src/NuGet.Core/NuGet.Packaging/Core/PackageDependencyInfo.cs
  src/NuGet.Core/NuGet.Packaging/PublicAPI/net472/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netcoreapp5.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
Labels: Community

#5307 Add apex test -- Install/Update/Uninstall vulnerable package from PMUI
  test/NuGet.Tests.Apex/NuGet.PackageManagement.UI.TestContract/ApexTestUIProject.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/Apex/NuGetUIProjectTestExtension.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetUITestCase.cs
Labels: Approved for CI

#5321 Fix case sensitivity of runtime dependency sets during merge
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/RuntimeDescription.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/RuntimeModelTests/RuntimeDescriptionTests.cs
Labels: bug, Approved for CI

#5322 Fix incorrect package version property for System.Security.Cryptograp…
  Directory.Packages.props
  eng/Version.Details.xml
Labels: Approved for CI, Community

#5324 Use singleton NuGetFrameworkSorter instance
  src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/Utils/InstalledPackageEnumerator.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/PackageReferenceProject.cs
  src/NuGet.Core/NuGet.Frameworks/CompatibilityListProvider.cs
  src/NuGet.Core/NuGet.Frameworks/FrameworkNameProvider.cs
  src/NuGet.Core/NuGet.Frameworks/FrameworkReducer.cs
  src/NuGet.Core/NuGet.Frameworks/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Frameworks/comparers/NuGetFrameworkSorter.cs
  src/NuGet.Core/NuGet.Packaging/NuspecReader.cs
  src/NuGet.Core/NuGet.Packaging/PackageReaderBase.cs
  src/NuGet.Core/NuGet.ProjectModel/PackageSpecWriter.cs
  src/NuGet.Core/NuGet.Protocol/Plugins/PluginPackageReader.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/PackCommandTests.cs
  test/NuGet.Core.Tests/NuGet.Frameworks.Test/FrameworkComparerTests.cs
  test/NuGet.Core.Tests/NuGet.Frameworks.Test/FrameworkExpanderTests.cs
  test/NuGet.Core.Tests/NuGet.Frameworks.Test/FrameworkNameProviderTests.cs
Labels: Perf

#5325 Remove allocations in hash code computations
  build/Shared/HashCodeCombiner.cs
  src/NuGet.Core/NuGet.Packaging/Core/FrameworkReferenceGroup.cs
  src/NuGet.Core/NuGet.Packaging/Core/FrameworkSpecificGroup.cs
  src/NuGet.Core/NuGet.Packaging/Core/PackageDependencyGroup.cs
  src/NuGet.Core/NuGet.Packaging/Core/comparers/PackageDependencyComparer.cs
  src/NuGet.Core/NuGet.Packaging/Core/comparers/PackageDependencyInfoComparer.cs
  src/NuGet.Core/NuGet.Packaging/Core/comparers/PackageIdentityComparer.cs
  src/NuGet.Core/NuGet.ProjectModel/CentralTransitiveDependencyGroup.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFile.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileLibrary.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileTarget.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileTargetLibrary.cs
  src/NuGet.Core/NuGet.ProjectModel/ProjectFileDependencyGroup.cs
  src/NuGet.Core/NuGet.Protocol/RemoteSourceDependencyInfo.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/Core/comparers/PackageDependencyInfoComparerTests.cs
Labels: Perf, Status:No recent activity
