Repository NuGet/NuGet.Client, pull requests merged in 2024-09, with the labels that each got.

#5982 Fix restore when a package is installed with a version specified in CPM
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/AddPackageReferenceCommandRunner.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetAddPackageTests.cs
Labels: Community

#6005 Improve build.sh and fixes for building on arm64 macOS
  build.sh
  build/DotNetSdkVersions.txt
Labels: Community

#6013 fix invalid argument error in NuGet performance script
  scripts/perftests/RunPerformanceTests.ps1
Labels: Engineering

#6008 Always debug RestoreTask and RestoreEx when environment variable is set
  src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/StaticGraphRestoreTaskBase.cs
Labels: Community

#6028 Properly handle missing package versions in new dependency resolver
  src/NuGet.Core/NuGet.Commands/RestoreCommand/DependencyGraphResolver.cs
  test/NuGet.Core.FuncTests/NuGet.Commands.FuncTest/RestoreCommand_AlgorithmEquivalencyTests.cs
Labels: Priority:1

#6035 Stop running tests in Official Build
  eng/pipelines/official.yml
Labels: Engineering

#6057 Disable code sign validation for non-shipping artifacts
  eng/pipelines/templates/pipeline.yml
Labels: Engineering

#6060 Set IsEscrowMode in release-6.12.x
  build/config.props
Labels: Engineering

#6059 Update Shipped APIs in release-6.12.x
  src/NuGet.Core/NuGet.Commands/PublicAPI/net472/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netcoreapp5.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netcoreapp5.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Common/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Common/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.DependencyResolver.Core/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.DependencyResolver.Core/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.PackageManagement/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.PackageManagement/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/net472/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netcoreapp5.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netcoreapp5.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Unshipped.txt
Labels: Engineering

#6061 Update branding in dev
  build/config.props
Labels: Engineering

#6062 Update Shipped APIs in dev
  src/NuGet.Core/NuGet.Commands/PublicAPI/net472/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netcoreapp5.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netcoreapp5.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Common/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Common/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.DependencyResolver.Core/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.DependencyResolver.Core/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.PackageManagement/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.PackageManagement/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/net472/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netcoreapp5.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netcoreapp5.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Unshipped.txt
Labels: Engineering
