Repository NuGet/NuGet.Client, pull requests merged in 2024-01, with the labels that each got.

#5550 Avoid boxing List<T> enumerator
  src/NuGet.Core/NuGet.Commands/RestoreCommand/LockFileBuilder.cs
Labels: Approved for CI, Community

#5551 Use string.Contains instead of IEnumerable.Contains
  src/NuGet.Core/NuGet.Versioning/VersionRangeFactory.cs
Labels: Approved for CI, Community

#5556 Switch from ConcurrentDictionary to Dictionary with lock to avoid rep…
  src/NuGet.Core/NuGet.Commands/RestoreCommand/SourceRepositoryDependencyProvider.cs
Labels: Approved for CI, Community

#5552 Avoid creating the capture class for calls to WithExtension
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/BuildAssetsUtils.cs
Labels: Approved for CI, Community

#5554 Switch from Tuple to ValueTuple for Dictionary keys
  src/NuGet.Core/NuGet.Commands/RestoreCommand/LockFileBuilder.cs
Labels: Approved for CI, Community

#5553 Avoid some allocations in GetCompatibilityData
  src/NuGet.Core/NuGet.Commands/RestoreCommand/CompatibilityChecker.cs
Labels: Approved for CI, Community

#5570 Always set ProjectPath in restore log messages, avoiding unnecessary assets file writes
  src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
  src/NuGet.Core/NuGet.Build.Tasks/CheckForDuplicateNuGetItemsTask.cs
  src/NuGet.Core/NuGet.Build.Tasks/Common/MSBuildLogger.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/RestoreCollectorLogger.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/AuditUtility.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/MSBuildRestoreUtility.cs
  src/NuGet.Core/NuGet.Common/Errors/RestoreLogMessage.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/AssetsLogMessage.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileFormat.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsSolutionRestoreServiceTests.cs
  test/NuGet.Core.FuncTests/Msbuild.Integration.Test/MsbuildRestoreTaskTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/CollectorLoggerTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/RestoreCommandTests/RestoreCommandTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/RestoreCommandTests/Utility/AuditUtilityTests.cs
Labels: Chat

#5568 Change ResolvedDependencyKey to a struct
  src/NuGet.Core/NuGet.Commands/GlobalSuppressions.cs
  src/NuGet.Core/NuGet.Commands/PublicAPI/net472/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netcoreapp5.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netcoreapp5.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Diagnostics/UnexpectedDependencyMessages.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/ResolvedDependencyKey.cs
Labels: Approved for CI, Community, Chat

#5589 Update the pool implementation to use a stack with a lock to avoid al…
  build/Shared/SimplePool.cs
Labels: Approved for CI, Community

#5588 Avoid boxing HashSet Enumerator in IsBestVerion
  build/Shared/NoAllocEnumerateExtensions.cs
  src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/Tracker.cs
  test/NuGet.Core.Tests/NuGet.Common.Test/NoAllocEnumerateExtensionsTests.cs
Labels: Approved for CI, Community

#5555 Unroll Linq in GetFlags
  src/NuGet.Core/NuGet.Packaging/NuspecReader.cs
Labels: Approved for CI, Community

#5600 Avoid intermediate string allocation caused by StringBuilder Append(i…
  src/NuGet.Core/NuGet.Versioning/VersionFormatter.cs
Labels: Approved for CI, Community
