Repository NuGet/NuGet.Client, pull requests merged in 2024-08, with the labels that each got.

#5911 Don't use obsolete X509Certificate2 constructor on net9.0
  eng/dotnet-build/global.json
  src/NuGet.Core/NuGet.Commands/SignCommand/CertificateProvider.cs
  src/NuGet.Core/NuGet.Configuration/Settings/Items/FileClientCertItem.cs
  src/NuGet.Core/NuGet.Packaging/Signing/Utility/CertificateChainUtility.cs
  test/NuGet.Core.Tests/NuGet.Configuration.Test/ClientCertificateProviderTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/HttpSource/ClientCertificatesTests.cs
  test/TestUtilities/Test.Utility/SelfSignedCertificateMockServer.cs
  test/TestUtilities/Test.Utility/Signing/SigningTestUtility.cs
  test/TestUtilities/Test.Utility/TestServer/TcpListenerServer.cs
Labels: Community

#5945 [CI] Re-enable Mac Mono Tests
  Directory.Packages.props
  eng/pipelines/ci.yml
  eng/pipelines/pull_request.yml
  eng/pipelines/templates/pipeline.yml
  scripts/funcTests/runFuncTests.sh
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGet.CommandLine.Test.csproj
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/xunit.runner.json
Labels: Engineering

#5923 Map SourceBranchName from sourcelink to RepositoryBranch for NuGet pack
  src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/PackCommandTests.cs
Labels: Community

#5956 Add System.Formats.Asn1 into Version.Details.xml
  eng/Version.Details.xml
Labels: Community, Engineering

#5934 add threat modeling section to the NuGet feature guide doc
  docs/feature-guide.md
Labels: Status:No recent activity

#5959 Allow override of System.Formats.Asn1 package version
  Directory.Packages.props
Labels: Community

#5963 Introduce optimized dependency graph resolution algorithm
  build/Shared/SharedStringBuilder.cs
  src/NuGet.Core/NuGet.Build.Tasks.Console/MSBuildStaticGraphRestore.cs
  src/NuGet.Core/NuGet.Commands/GlobalSuppressions.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/DependencyGraphResolver.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/ProjectRestoreCommand.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreTargetGraph.cs
  src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/GraphNode.cs
  src/NuGet.Core/NuGet.DependencyResolver.Core/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.DependencyResolver.Core/Remote/RemoteDependencyWalker.cs
  src/NuGet.Core/NuGet.ProjectModel/PackageSpecOperations.cs
  src/NuGet.Core/NuGet.Versioning/NuGet.Versioning.csproj
  src/NuGet.Core/NuGet.Versioning/VersionFormatter.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeFormatter.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreTransitiveLoggingTests.cs
Labels: Priority:1

#5966 Install all packages during dependency walk in new resolver
  src/NuGet.Core/NuGet.Commands/RestoreCommand/DependencyGraphResolver.cs
Labels: Priority:1

#5967 Fix new resolver reporting downgrades for pinned packages that have PrivateAssets=All
  src/NuGet.Core/NuGet.Commands/RestoreCommand/DependencyGraphResolver.cs
Labels: Priority:1

#5968 Fix problem in new resolver with pinned package and version override
  src/NuGet.Core/NuGet.Commands/RestoreCommand/DependencyGraphResolver.cs
Labels: Priority:1

#5957 Update darc BAR tokens authentication method
  build/publish.proj
  eng/pipelines/templates/Build_and_UnitTest.yml
Labels: Status:No recent activity

#5973 Fix publish.proj to not require MaestroAccessToken and MaestroApiEndpoint
  build/publish.proj
Labels: Priority:1

#5976 Update Microsoft.DotNet.Maestro.Tasks package and bring back MaestroApiEndpoint parameter
  Directory.Packages.props
  build/publish.proj
  eng/pipelines/templates/Build_and_UnitTest.yml
Labels: Engineering, Priority:1

#5962 Pack ContentItem with fields
  src/NuGet.Core/NuGet.Commands/RestoreCommand/LockFileBuilder.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs
  src/NuGet.Core/NuGet.Packaging/ContentModel/ContentItem.cs
  src/NuGet.Core/NuGet.Packaging/ContentModel/ContentItemCollection.cs
  src/NuGet.Core/NuGet.Packaging/ContentModel/Infrastructure/Parser.cs
  src/NuGet.Core/NuGet.Packaging/NuGet.Packaging.csproj
  src/NuGet.Core/NuGet.Packaging/PublicAPI/net472/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netcoreapp5.0/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  test/NuGet.Core.Tests/NuGet.Packaging.Test/ContentModelTests/ContentItemTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/InvalidUndottedFrameworkRuleTests.cs
Labels: Learning Opportunity

#5983 Disable flaky tests, PushCommand_PushToServerWontRetryForever and PushCommand_PushToServer_GetCredentialFromPlugin, and extend timeout to Run_CanGetExitCode
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/CommandRunnerTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPushCommandTest.cs
Labels: Engineering

#5974 Modernize the performance scripts - add the ability to test a locally built NuGet
  scripts/perftests/PerformanceTestRunner.ps1
  scripts/perftests/PerformanceTestUtilities.ps1
  scripts/perftests/README.md
  scripts/perftests/RunPerformanceTests.ps1
  scripts/perftests/testCases/Test-NuGetClient.ps1
  scripts/perftests/testCases/Test-OrchardCore.ps1
  scripts/perftests/testCases/Test-Orleans.ps1
Labels: Engineering
