Repository NuGet/NuGet.Client, pull requests merged in 2024-02, with the labels that each got.

#5619 Reduces some CPU time usage in SetCentralDependencies
  src/NuGet.Core/NuGet.ProjectModel/PackageSpecWriter.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/compiler/resources/DependencyGraphSpec_CentralVersionDependencies.json
Labels: Approved for CI, Community

#5592 Avoid multiple enumeration when writing Json objects
  src/NuGet.Core/NuGet.Packaging/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netcoreapp5.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Packaging/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/IObjectWriter.cs
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/JsonObjectWriter.cs
  src/NuGet.Core/NuGet.ProjectModel/HashObjectWriter.cs
  src/NuGet.Core/NuGet.ProjectModel/PackageSpecWriter.cs
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Unshipped.txt
  test/NuGet.Core.Tests/NuGet.Packaging.Test/RuntimeModelTests/JsonObjectWriterTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/HashObjectWriterTests.cs
Labels: Approved for CI, Community

#5593 Further reduce allocations in CreateGraphNodeAsync
  src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/GraphNode.cs
  src/NuGet.Core/NuGet.DependencyResolver.Core/Remote/RemoteDependencyWalker.cs
Labels: Approved for CI, Community

#5574 Unroll several LINQ calls
  src/NuGet.Core/NuGet.Commands/RestoreCommand/MSBuildRestoreItemGroup.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/BuildAssetsUtils.cs
Labels: Approved for CI, Community

#5569 Make PMUI packages browse page to allow loading additional packages
  src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/InfiniteScrollList.xaml.cs
Labels: Status:No recent activity

#5585 Create a Apex daily test pipeline that triggered by NuGet.Client Official
  NuGet-ApexTests.slnf
  NuGet.sln
  build/runsettings.proj
  eng/pipelines/dailytests.yml
  eng/pipelines/templates/Apex_Tests_On_Windows_Daily.yml
  eng/pipelines/templates/Build_and_UnitTest.yml
  test/NuGet.Tests.Apex/NuGet.Tests.Apex.Daily/NuGet.Tests.Apex.Daily.csproj
  test/NuGet.Tests.Apex/NuGet.Tests.Apex.Daily/NuGetEndToEndTests/NuGetUITestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/Apex/ApexTestContext.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/Apex/SharedVisualStudioHostTestClass.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/Utility/CommonUtility.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/VisualStudioHostExtension.cs
Labels: Approved for CI

#5625 Eliminate System.CommandLine prebuilt package
  eng/Version.Details.xml
Labels: Approved for CI, Community

#5584 Unroll LINQ usage to trim some allocations in AddMSBuildAssets
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs
Labels: Approved for CI, Community

#5629 Replace calls to Any() on ICollection in PackageSpecWriter with Count > 0 Issue #13213
  src/NuGet.Core/NuGet.ProjectModel/PackageSpecWriter.cs
Labels: Approved for CI, Community

#5624 Switch CreateNodeAsync to an iterative approach
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Diagnostics/UnexpectedDependencyMessages.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/BuildAssetsUtils.cs
  src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/GraphNode.cs
  src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/Tracker.cs
  src/NuGet.Core/NuGet.DependencyResolver.Core/Remote/RemoteDependencyWalker.cs
  src/NuGet.Core/NuGet.Frameworks/FrameworkNameProvider.cs
  src/NuGet.Core/NuGet.Packaging/ContentModel/ManagedCodeConventions.cs
  src/NuGet.Core/NuGet.Packaging/RuntimeModel/RuntimeGraph.cs
  test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/TrackerTests.cs
Labels: Approved for CI, Community

#5650 Add Restore Instrumentation
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreResult.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreRunner.cs
  src/NuGet.Core/NuGet.Common/NuGetEventSource.cs
  src/NuGet.Core/NuGet.Common/PublicAPI.Unshipped.txt
Labels: Approved for CI, Community
