Repository NuGet/NuGet.Client, pull requests merged in 2024-10, with the labels that each got.

#5953 Pull Request Etiquette and Best Practices
  docs/workflow.md
Labels: Status:No recent activity

#6087 Skip PushCommand_AllowsTimeoutToBeSpecifiedHigherThan100Seconds and PushCommand_AllowsTimeoutToBeSpecifiedLowerThan100Seconds
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/PushCommandTest.cs
Labels: Engineering

#6080 Upload binary logs in CI for cancellations
  eng/pipelines/pr.job.yml
Labels: Engineering

#6018 Update _WalkEachTargetPerFramework to walk TFMs in parallel
  src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets
Labels: Community

#6097 Disable GetPackageSpec_WithInvalidUsingMicrosoftNetSdk_ThrowsAnException as it's flaky.
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/JsonPackageSpecReaderTests.cs
Labels: Engineering

#6096 Split up functional test execution in CI
  Directory.Build.targets
  Directory.Solution.targets
  eng/pipelines/pr.job.yml
  eng/pipelines/pr.yml
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/NuGet.CommandLine.FuncTest.csproj
  test/NuGet.Clients.FuncTests/NuGet.MSSigning.Extensions.FuncTest/NuGet.MSSigning.Extensions.FuncTest.csproj
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPushCommandTest.cs
  test/NuGet.Core.FuncTests/NuGet.Commands.FuncTest/NuGet.Commands.FuncTest.csproj
  test/NuGet.Core.FuncTests/NuGet.Protocol.FuncTest/NuGet.Protocol.FuncTest.csproj
  test/NuGet.Core.FuncTests/NuGet.Signing.CrossFramework.Test/NuGet.Signing.CrossFramework.Test.csproj
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/NuGet.XPlat.FuncTest.csproj
  test/NuGet.Core.Tests/NuGet.PackageManagement.Test/NuGet.PackageManagement.Test.csproj
Labels: Engineering

#6102 Update source-build team references
  eng/SourceBuildPrebuiltBaseline.xml
Labels: Community

#6072 add SpecialFolder.UserProfile fallback
  src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs
Labels: Community

#6104 Disable NuGetPushCommandTest.PushCommand_PushTimeoutErrorMessage
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPushCommandTest.cs
Labels: Engineering

#6106 E2E Test: Fix solution folder name comparison
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectServices/VsProjectBuildProperties.cs
  test/TestExtensions/API.Test/VSSolutionHelper.cs
Labels: Engineering

#6105 Do not run tests in isolation
  build/xunit.runsettings
  eng/pipelines/pr.job.yml
Labels: Engineering

#6108 Use .NET SDK 8.0.4xx to build and test
  build/DotNetSdkVersions.txt
Labels: Engineering

#6098 Modify ContentItemCollection.PopulateItemGroups to use pooling for highly allocated temporary data structures
  src/NuGet.Core/NuGet.Packaging/ContentModel/ContentItemCollection.cs
  src/NuGet.Core/NuGet.Packaging/NuGet.Packaging.csproj
Labels: Community

#6128 Disable manual GitHub status for PrivateDev
  eng/pipelines/pull_request.yml
Labels: Engineering

#6124 Expand Locale parser to support three-character language codes
  src/NuGet.Core/NuGet.Packaging/ContentModel/ManagedCodeConventions.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/ContentModelTests/ContentModelResourceTests.cs
Labels: Community
