Repository NuGet/NuGet.Client, pull requests merged in 2024-07, with the labels that each got.

#5862 Reduce allocations for version / versionranges
  src/NuGet.Core/NuGet.Versioning/NuGetVersionFactory.cs
  src/NuGet.Core/NuGet.Versioning/VersionRangeFactory.cs
Labels: Community

#5874 Attempt to make functional tests more reliable
  Directory.Solution.targets
  build/TestShared/xunit.runner.json
  build/build.proj
  build/test.targets
  build/xunit.runsettings
  eng/pipelines/pr.job.yml
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/NuGet.CommandLine.FuncTest.csproj
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGet.CommandLine.Test.csproj
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPackCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.Indexing.Test/NuGet.Indexing.Test.csproj
  test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/NuGet.PackageManagement.UI.Test.csproj
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/NuGet.PackageManagement.VisualStudio.Test.csproj
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/NuGet.SolutionRestoreManager.Test.csproj
  test/NuGet.Clients.Tests/NuGet.Tools.Test/NuGet.Tools.Test.csproj
  test/NuGet.Clients.Tests/NuGet.VisualStudio.Common.Test/NuGet.VisualStudio.Common.Test.csproj
  test/NuGet.Clients.Tests/NuGet.VisualStudio.Test/NuGet.VisualStudio.Test.csproj
  test/NuGet.Clients.Tests/NuGetConsole.Host.PowerShell.Test/NuGetConsole.Host.PowerShell.Test.csproj
  test/NuGet.Core.FuncTests/Msbuild.Integration.Test/Msbuild.Integration.Test.csproj
  test/NuGet.Core.FuncTests/NuGet.Commands.FuncTest/NuGet.Commands.FuncTest.csproj
  test/NuGet.Core.FuncTests/NuGet.Packaging.FuncTest/NuGet.Packaging.FuncTest.csproj
  test/NuGet.Core.FuncTests/NuGet.Protocol.FuncTest/NuGet.Protocol.FuncTest.csproj
  test/NuGet.Core.FuncTests/NuGet.Signing.CrossFramework.Test/NuGet.Signing.CrossFramework.Test.csproj
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/NuGet.XPlat.FuncTest.csproj
  test/NuGet.Core.Tests/Microsoft.Build.NuGetSdkResolver.Test/Microsoft.Build.NuGetSdkResolver.Test.csproj
  test/NuGet.Core.Tests/NuGet.Build.Tasks.Console.Test/NuGet.Build.Tasks.Console.Test.csproj
  test/NuGet.Core.Tests/NuGet.Build.Tasks.Pack.Test/NuGet.Build.Tasks.Pack.Test.csproj
  test/NuGet.Core.Tests/NuGet.Build.Tasks.Test/NuGet.Build.Tasks.Test.csproj
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/NuGet.CommandLine.Xplat.Tests.csproj
  test/NuGet.Core.Tests/NuGet.Commands.Test/NuGet.Commands.Test.csproj
  test/NuGet.Core.Tests/NuGet.Common.Test/NuGet.Common.Test.csproj
  test/NuGet.Core.Tests/NuGet.Configuration.Test/NuGet.Configuration.Test.csproj
  test/NuGet.Core.Tests/NuGet.Credentials.Test/NuGet.Credentials.Test.csproj
  test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/NuGet.DependencyResolver.Core.Tests.csproj
  test/NuGet.Core.Tests/NuGet.Frameworks.Test/NuGet.Frameworks.Test.csproj
  test/NuGet.Core.Tests/NuGet.LibraryModel.Tests/NuGet.LibraryModel.Tests.csproj
  test/NuGet.Core.Tests/NuGet.PackageManagement.Test/NuGet.PackageManagement.Test.csproj
  test/NuGet.Core.Tests/NuGet.Packaging.Test/NuGet.Packaging.Test.csproj
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/NuGet.ProjectModel.Test.csproj
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/NuGet.Protocol.Tests.csproj
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/Plugins/Logging/TaskLogMessageTests.cs
  test/NuGet.Core.Tests/NuGet.Resolver.Test/NuGet.Resolver.Test.csproj
  test/NuGet.Core.Tests/NuGet.Shared.Tests/NuGet.Shared.Tests.csproj
  test/NuGet.Core.Tests/NuGet.Versioning.Test/NuGet.Versioning.Test.csproj
  test/TestUtilities/Test.Utility/CommandRunner.cs
Labels: Engineering, Learning Opportunity

#5902 Disable CodeQL
  eng/pipelines/pr.yml
Labels: Engineering

#5901 Reduce console output when running tests and update more tests to use ITestOutputHelper
  src/NuGet.Core/NuGet.CommandLine.XPlat/ListPackage/ListPackageConsoleRenderer.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/ListPackage/ListPackageJsonRenderer.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetRestoreTLSCertificateValidationTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/BasicLoggingTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/ListPackageTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/TestCommandOutputLogger.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatAddPkgTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatClientCertTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatHelpOutputTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatPushTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatTestUtils.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatTrustTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatVerifyTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatWhyTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XplatRemovePkgTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XplatSignTests.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/ListPackageCommandRunnerTests.cs
  test/TestUtilities/Test.Utility/SelfSignedCertificateMockServer.cs
Labels: Engineering

#5905 Fix race condition in EnhancedHttpRetryHelper
  src/NuGet.Core/NuGet.Protocol/EnhancedHttpRetryHelper.cs
Labels: Community

#5904 Move static source analysis to CI pipeline from PrivateDev
  NuGet.sln
  eng/pipelines/pr.yml
  eng/pipelines/pull_request.yml
  eng/pipelines/templates/pipeline.yml
Labels: Engineering

#5906 Update the debug helper scripts to import the props file
  scripts/nuget-debug-helpers.ps1
Labels: Engineering

#5914 Cleanup unused packages from Directory.Packages.props
  Directory.Packages.props
  src/NuGet.Core/NuGet.CommandLine.XPlat/NuGet.CommandLine.XPlat.csproj
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGet.CommandLine.Test.csproj
Labels: Engineering

#5833 Add SDKAnalysisLevel and UsingMicrosoftNETSdk to packageSpec
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/LegacyPackageReferenceProject.cs
  src/NuGet.Clients/NuGet.SolutionRestoreManager/VSNominationUtilities.cs
  src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
  src/NuGet.Core/NuGet.Build.Tasks.Console/MSBuildStaticGraphRestore.cs
  src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets
  src/NuGet.Core/NuGet.Build.Tasks/Strings.resx
  src/NuGet.Core/NuGet.Commands/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netcoreapp5.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/MSBuildRestoreUtility.cs
  src/NuGet.Core/NuGet.Commands/Strings.Designer.cs
  src/NuGet.Core/NuGet.Commands/Strings.resx
  src/NuGet.Core/NuGet.PackageManagement/Projects/ProjectBuildProperties.cs
  src/NuGet.Core/NuGet.PackageManagement/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.Utf8JsonStreamReader.cs
  src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs
  src/NuGet.Core/NuGet.ProjectModel/PackageSpecWriter.cs
  src/NuGet.Core/NuGet.ProjectModel/ProjectRestoreMetadata.cs
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.ProjectModel/Strings.Designer.cs
  src/NuGet.Core/NuGet.ProjectModel/Strings.resx
  src/NuGet.Core/NuGet.ProjectModel/Utf8JsonStreamReader.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/ProjectSystems/LegacyPackageReferenceProjectTests.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VSNominationUtilitiesTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/MSBuildRestoreUtilityTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/JsonPackageSpecReaderTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/LockFileFormatTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/PackageSpecTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/PackageSpecWriterTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/compiler/resources/DependencyGraphSpec_CentralVersionDependencies.json
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/compiler/resources/DependencyGraphSpec_Save_SerializesMembersAsJson.json
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/compiler/resources/PackageSpecWriter_Write_SerializesMembersAsJson.json
Labels: Priority:1

#5927 Remove "please" from http-errors
  src/NuGet.Clients/NuGet.CommandLine/NuGetResources.Designer.cs
  src/NuGet.Clients/NuGet.CommandLine/NuGetResources.resx
  src/NuGet.Core/NuGet.Commands/Strings.Designer.cs
  src/NuGet.Core/NuGet.Commands/Strings.resx
  src/NuGet.Core/NuGet.PackageManagement/Strings.Designer.cs
  src/NuGet.Core/NuGet.PackageManagement/Strings.resx
Labels: Priority:1

#5922 Allow passing assets file directly to dotnet nuget why
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/WhyCommand/WhyCommandRunner.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Strings.Designer.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Strings.resx
  src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/XPlatUtility.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetIntegrationTestFixture.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetWhyTests.cs
Labels: Priority:1

#5925 Use SdkAnalysisLevel in restorecommand http-errors
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
  src/NuGet.Core/NuGet.Commands/Utility/SdkAnalysisLevelMinimums.cs
  test/NuGet.Core.FuncTests/NuGet.Commands.FuncTest/RestoreCommandTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/SdkAnalysisLevelMinimumsTests.cs
Labels: Priority:1

#5940 Account for InvalidOperationException in XunitLogger
  test/TestUtilities/Test.Utility/XunitLogger.cs
Labels: Engineering

#5941 Update version of .NET SDK used for build to 8.0.3xx
  build/DotNetSdkVersions.txt
Labels: Engineering

#5942 Disable Static Analysis status check if its not being run
  scripts/utils/PostGitCommitStatus.ps1
Labels: Engineering
