Repository NuGet/NuGet.Client, pull requests merged in 2024-06, with the labels that each got.

#5848 Dispose certificates on failure in SignatureUtility.GetCertificates
  src/NuGet.Core/NuGet.Packaging/Signing/Utility/SignatureUtility.cs
Labels: Community

#5859 Reduce allocations in GetPackageInfo by conditionally calling GetNupkgMetadataPath
  src/NuGet.Core/NuGet.Packaging/FallbackPackagePathResolver.cs
Labels: Community

#5865 Change the project template for test cases using IOS to Maui
  build/tests.dev17.vsconfig
  test/NuGet.Tests.Apex/NuGet.Tests.Apex.Daily/NuGetConsoleTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex.Daily/NuGetUITestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetConsoleTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetUITestCase.cs
Labels: Engineering

#5861 Defer LockFileItem.Properties dictionary construction until needed
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileItem.cs
Labels: Community

#5868 Run source build in CI pipeline
  eng/pipelines/pr.yml
  eng/pipelines/pull_request.yml
  scripts/utils/PostGitCommitStatus.ps1
Labels: Engineering

#5866 Fix ability for individual projects to enable or disable Central Package Management
  src/NuGet.Core/NuGet.Build.Tasks/NuGet.props
  test/NuGet.Core.FuncTests/Msbuild.Integration.Test/MsbuildIntegrationTestFixture.cs
  test/NuGet.Core.FuncTests/Msbuild.Integration.Test/MsbuildRestoreTaskTests.cs
Labels: Priority:1

#5857 Reduce memory allocations during solution load in VS
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/PackageReferenceProject.cs
  src/NuGet.Core/NuGet.ProjectModel/GlobalSuppressions.cs
  src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.Utf8JsonStreamReader.cs
  src/NuGet.Core/NuGet.ProjectModel/JsonUtility.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileFormat.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileReadFlags.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileUtilities.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/Utf8JsonStreamLockFileConverter.cs
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Unshipped.txt
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/LockFileFormatTests.cs
Labels: Community

#5869 fix legacy project restore error from visual studio
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/LegacyPackageReferenceProject.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/ProjectSystems/LegacyPackageReferenceProjectTests.cs
Labels: Community

#5886 [release-6.11.x] CI: ShouldSkipOptimize is not a compile time variable (#5884)
  eng/pipelines/templates/pipeline.yml
Labels: Engineering

#5887 CI: ShouldSkipOptimize is not a compile time variable (#5884)
  eng/pipelines/templates/pipeline.yml
Labels: Engineering
