Repository NuGet/NuGet.Client, pull requests merged in 2025-03, with the labels that each got.

#6294 Reduce activity log output from VsSolutionRestoreService.NominateProjectAsync
  src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs
Labels: Community

#6299 Stop publishing assets to .NET BAR for release-5.11.x branch
  NuGet.Config
  build/bootstrap.proj
  build/publish.proj
  eng/pipelines/templates/Build_and_UnitTest.yml
Labels: Engineering

#6305 Set build number to arcade build revision for VMR builds
  eng/dotnet-build/dotnet-build.proj
Labels: Community

#6309 Define MicrosoftVisualStudioSolutionPersistenceVersion property
  Directory.Packages.props
Labels: Community, Engineering

#6310 Simplify the project reference graph in src\NuGet.Clients
  src/NuGet.Clients/NuGet.Console/NuGet.Console.csproj
  src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/NuGet.PackageManagement.PowerShellCmdlets.csproj
  src/NuGet.Clients/NuGet.PackageManagement.UI/NuGet.PackageManagement.UI.csproj
  src/NuGet.Clients/NuGet.SolutionRestoreManager/NuGet.SolutionRestoreManager.csproj
  src/NuGet.Clients/NuGet.Tools/NuGet.Tools.csproj
  src/NuGet.Clients/NuGet.VisualStudio.OnlineEnvironment.Client/NuGet.VisualStudio.OnlineEnvironment.Client.csproj
Labels: Engineering

#6331 Create Branch Classification policy
  .azuredevops/policies/branchClassification.yml
Labels: Engineering

#6333 Configure SBOM for Build pipeline
  eng/common/generate-sbom-prep.ps1
  eng/common/templates/steps/generate-sbom.yml
  eng/pipelines/official.yml
  eng/pipelines/pull_request.yml
  eng/pipelines/templates/Build_and_UnitTest.yml
  eng/pipelines/templates/pipeline.yml
  eng/pipelines/vs-test/build.yml
Labels: Engineering

#6338 Update ngen Priorities for VS
  src/NuGet.Clients/NuGet.VisualStudio.Client/NuGet.VisualStudio.Client.csproj
Labels: Community

#6357 Remove manual GitHub status checks functionality from all pipelines
  eng/pipelines/pull_request.yml
  eng/pipelines/templates/Build_and_UnitTest.yml
  eng/pipelines/templates/CrossFramework_Tests_On_Windows.yml
  eng/pipelines/templates/Functional_Tests_On_Windows.yml
  eng/pipelines/templates/Initialize_Build.yml
  eng/pipelines/templates/Initialize_Build_SemanticVersion.yml
  eng/pipelines/templates/Source_Build.yml
  eng/pipelines/templates/Static_Source_Analysis.yml
  eng/pipelines/templates/Tests_On_Linux.yml
  eng/pipelines/templates/Tests_On_Mac.yml
  eng/pipelines/vs-test/apex.yml
  eng/pipelines/vs-test/build.yml
  eng/pipelines/vs-test/end_to_end.yml
  eng/pipelines/vs-tests.yml
  scripts/utils/PostGitCommitStatus.ps1
Labels: Engineering
