Repository NuGet/NuGet.Client, pull requests merged in 2025-08, with the labels that each got.

#6643 remove MsBuildUtility.GetMsBuildPathInPathVar
  src/NuGet.Clients/NuGet.CommandLine/GlobalSuppressions.cs
  src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs
Labels: Community

#6613 remove redundant type variable in GetExternalProject
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/DependencyGraphSpecRequestProvider.cs
Labels: Community

#6606 enable nullable in VSNominationUtilitiesTests
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VSNominationUtilitiesTests.cs
Labels: Community

#6600 enable nullable in NuGetUpdateCommandTests
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetUpdateCommandTests.cs
Labels: Community

#6574 remove redundant dictionary lookup in CreatePackageSourceMappingDictionary
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Options/PackageSourceMappingUtility.cs
Labels: Community

#6626 remove un-used variables in SignedPackageArchiveIOUtility
  src/NuGet.Core/NuGet.Packaging/Signing/Archive/SignedPackageArchiveIOUtility.cs
Labels: Community

#6694 remove unused parameter
  eng/pipelines/vs-test/build.yml
Labels: Engineering

#6695 Use .NET 10 for publish.proj tasks
  eng/pipelines/templates/Build_and_UnitTest.yml
Labels: Engineering

#6641 remove redundant null condition in UpdateCommand.ExecuteCommandAsync
  src/NuGet.Clients/NuGet.CommandLine/Commands/UpdateCommand.cs
Labels: Community

#6602 enable nullable in MSBuildUtilityTest
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/MSBuildUtilityTest.cs
Labels: Community

#6637 remove PackageManagerControl.AddMigratorBar
  src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageManagerControl.xaml.cs
Labels: Community

#6640 remove redundant exception handling
  src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs
  src/NuGet.Core/NuGet.Packaging/PackageExtractor.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/FeedPackagePruningTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/PackageFeeds/PackageSourceMonikerTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/HttpSource/HttpSourceAuthenticationHandlerTests.cs
  test/TestUtilities/Microsoft.Internal.NuGet.Testing.SignedPackages/TestServer/PortReserver.cs
  test/TestUtilities/Test.Utility/FileSystemBackedV3MockServer.cs
Labels: Community

#6619 remove unused packageID variable
  src/NuGet.Clients/NuGet.CommandLine/Commands/InitCommand.cs
Labels: Community

#6623 remove redundant GetManifestResourceNames in ManifestSchemaUtility
  src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestSchemaUtility.cs
Labels: Community

#6635 remove EnvDteProjectExtensions.PathComparer
  src/NuGet.Clients/NuGet.VisualStudio.Common/IDE/EnvDteProjectExtensions.cs
Labels: Community

#6631 remove DependencyGraphSpecRequestProvider.CollectReferences
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/DependencyGraphSpecRequestProvider.cs
Labels: Community

#6628 remove redundant enumeration in CredentialsItem
  src/NuGet.Core/NuGet.Configuration/Settings/Items/CredentialsItem.cs
Labels: Community

#6608 remove un-used contextForGather
  src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
Labels: Community

#6609 fix nullability in UnresolvedMessages
  src/NuGet.Core/NuGet.Commands/RestoreCommand/Diagnostics/UnresolvedMessages.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/UnresolvedMessagesTests.cs
Labels: Community

#6625 remove un-used variables in PackageExtractor
  src/NuGet.Core/NuGet.Packaging/PackageExtractor.cs
Labels: Community

#6593 enable nullable in IProjectContextInfoExtensionsTests
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Common/IProjectContextInfoExtensionsTests.cs
Labels: Community

#6601 enable nullabe in NuGetInstallCommandTest
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetInstallCommandTest.cs
Labels: Community

#6575 remove redundant dictionary lookup in CredentialServiceAdapter.GetCredentials
  src/NuGet.Clients/NuGet.CommandLine/Credentials/CredentialServiceAdapter.cs
Labels: Community

#6589 redundant null check for projectManagerService.GetMetadataAsync return value
  src/NuGet.Clients/NuGet.PackageManagement.UI/Actions/UIActionEngine.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/Actions/UIActionEngineTests.cs
Labels: Community

#6622 remove un-used list in GetPackagesToBeReinstalled
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Utility/ProjectRetargetingUtility.cs
Labels: Community

#6577 use fields instead of private properties
  src/NuGet.Clients/NuGet.Console/PowerConsole/HostInfo.cs
  src/NuGet.Clients/NuGet.Console/WpfConsole/WpfConsole.cs
  src/NuGet.Clients/NuGet.Console/WpfConsole/WpfConsoleClassifier.cs
  src/NuGet.Clients/NuGet.Console/WpfConsole/WpfConsoleCompletionSource.cs
  src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/Cmdlets/UpdatePackageCommand.cs
  src/NuGet.Clients/NuGet.PackageManagement.UI/InfiniteScrollListItemStyleSelector.cs
  src/NuGet.Clients/NuGet.PackageManagement.UI/Models/LicenseFileData.cs
  src/NuGet.Clients/NuGet.PackageManagement.UI/ViewModels/PackageDetailsTabViewModel.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/PackageFeeds/RecommenderPackageFeed.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/VsMSBuildProjectSystem.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Runtime/BindingRedirectManager.cs
  src/NuGet.Clients/NuGet.Tools/NuGetPackage.cs
  src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstaller.cs
  src/NuGet.Core/NuGet.Commands/MSBuildProjectFactory.cs
  src/NuGet.Core/NuGet.Commands/PackCollectorLogger.cs
  src/NuGet.Core/NuGet.PackageManagement/Projects/FolderNuGetProject.cs
  src/NuGet.Core/NuGet.PackageManagement/Projects/PackagesConfigNuGetProject.cs
  src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PhysicalPackageFile.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/TestPackageSourceProvider.cs
  test/NuGet.Core.Tests/NuGet.PackageManagement.Test/BuildIntegration/TestPackageReferenceNuGetProject.cs
  test/TestUtilities/Test.Utility/ProjectManagement/TestMSBuildNuGetProjectSystem.cs
  test/TestUtilities/Test.Utility/SourceRepository/TestSourceRepositoryUtility.cs
Labels: Community

#6709 Disable flaky test - NuGet.Packaging.Test.PackageExtraction.ZipArchiveExtensionsTests.UpdateFileTimeFromEntry_FileBusyForShortTime_Retries
  test/NuGet.Core.Tests/NuGet.Packaging.Test/PackageExtraction/ZipArchiveExtensionsTests.cs
Labels: Engineering

#6708 Use test signing for vs-test legs
  eng/pipelines/vs-test/build.yml
Labels: Engineering

#6587 remove redundant dictionary lookup in ProcessUnrankedEntries
  src/NuGet.Clients/NuGet.Indexing/RelevanceSearchResultsIndexer.cs
Labels: Community

#6634 remove IFrameworkTargetable
  src/NuGet.Clients/NuGet.CommandLine/ilmerge.props
  src/NuGet.Clients/NuGet.MSSigning.Extensions/ilmerge.props
  src/NuGet.Core/NuGet.Frameworks/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.Frameworks/def/IFrameworkTargetable.cs
Labels: Community

#6735 Disable loading profile in utility powershell.exe calls
  build/common.ps1
  src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/NuGet.PackageManagement.PowerShellCmdlets.csproj
Labels: Community, Engineering

#6581 remove redundant dictionary lookups in MarkTransitiveOrigin
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/PackageReferenceProject.cs
Labels: Community

#6610 add "does not have a min version" to messages in GetNupkgInfo
  tools-local/ensure-nupkg-dependencies-on-source/Program.cs
Labels: Community

#6747 Fix the VsTargetChannelForTests setting for 'main' insertion
  build/config.props
Labels: Engineering
