Repository NuGet/NuGet.Client, pull requests merged in 2025-04, with the labels that each got.

#6373 Use RC label in the build branding
  build/config.props
Labels: Engineering

#6375 Stop setting CurrentDirectory in TestFileSystemUtility
  src/NuGet.Core/NuGet.Common/GlobalSuppressions.cs
  src/NuGet.Core/NuGet.Common/PathUtil/PathUtility.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatPushTests.cs
  test/TestUtilities/Test.Utility/TestFileSystemUtility.cs
Labels: Engineering

#6379 Update version to 6.15
  build/config.props
  src/NuGet.Clients/NuGet.VisualStudio.Client/source.extension.vsixmanifest
Labels: Engineering

#6382 Run integration test against .NET 10
  build/DotNetSdkTestVersions.txt
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/Constants.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetListPackageTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetSignTests.cs
  test/NuGet.Core.FuncTests/NuGet.Signing.CrossFramework.Test/CrossVerifyTestFixture.cs
  test/TestUtilities/Test.Utility/TestDotnetCLiUtility.cs
Labels: Engineering

#6387 Debug helper scripts should use net9.0
  scripts/nuget-debug-helpers.ps1
Labels: Engineering

#6386 Small updates for the VMR
  NuGet.sln
  eng/DotNetBuild.props
  eng/Publishing.props
  eng/dotnet-build/dotnet-build.proj
Labels: Community, Engineering

#6236 Update System.CommandLine
  Directory.Packages.props
  eng/Version.Details.xml
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/ConfigCommands/ConfigCommand.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/DocumentedCommand.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageSearch/PackageSearchCommand.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/Why/WhyCommand.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/GlobalSuppressions.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Program.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/PublicAPI.Shipped.txt
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/Dotnet.Integration.Test.csproj
  test/NuGet.Core.FuncTests/NuGet.Signing.CrossFramework.Test/NuGet.Signing.CrossFramework.Test.csproj
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/Commands/Why/WhyCommandLineParsingTests.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/Commands/config/ConfigCommandTests.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/PackageSearchTestInitializer.cs
  tools-local/ensure-nupkg-dependencies-on-source/Program.cs
  tools-local/ship-public-apis/Program.cs
Labels: Community

#6321 Add support for SLNX solution file format in NuGet.exe
  src/NuGet.Clients/NuGet.CommandLine/Commands/RestoreCommand.cs
  src/NuGet.Clients/NuGet.CommandLine/Commands/UpdateCommand.cs
  src/NuGet.Clients/NuGet.CommandLine/Common/ProjectHelper.cs
  src/NuGet.Clients/NuGet.CommandLine/NuGetResources.Designer.cs
  src/NuGet.Clients/NuGet.CommandLine/NuGetResources.resx
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/RestoreCommandTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetUpdateCommandTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/Util.cs
Labels: Community

#6402 Support the verbosity flag in nuget-client VMR entry-point
  eng/dotnet-build/build.ps1
  eng/dotnet-build/build.sh
Labels: Community

#6407 Update package Category
  eng/Publishing.props
Labels: Community, Engineering

#6409 Change the for each pattern being used in EmitIfNeeded_MultipleThreads_EmitsOnceAsync
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Telemetry/TelemetryOnceEmitterTests.cs
Labels: Engineering

#6413 Fix 6.11 build, remove manual GH checks and use the correct ubuntu pool
  eng/pipelines/pr.yml
  eng/pipelines/templates/Apex_Tests_On_Windows.yml
  eng/pipelines/templates/Build_and_UnitTest.yml
  eng/pipelines/templates/CrossFramework_Tests_On_Windows.yml
  eng/pipelines/templates/End_To_End_Tests_On_Windows.yml
  eng/pipelines/templates/Functional_Tests_On_Windows.yml
  eng/pipelines/templates/Initialize_Build.yml
  eng/pipelines/templates/Initialize_Build_SemanticVersion.yml
  eng/pipelines/templates/Source_Build.yml
  eng/pipelines/templates/Static_Source_Analysis.yml
  eng/pipelines/templates/Tests_On_Linux.yml
  eng/pipelines/templates/Tests_On_Mac.yml
  scripts/utils/PostGitCommitStatus.ps1
Labels: Engineering

#6414 Fix 6.10 build, remove manual GH checks
  eng/pipelines/templates/Apex_Tests_On_Windows.yml
  eng/pipelines/templates/Build_and_UnitTest.yml
  eng/pipelines/templates/CrossFramework_Tests_On_Windows.yml
  eng/pipelines/templates/End_To_End_Tests_On_Windows.yml
  eng/pipelines/templates/Functional_Tests_On_Windows.yml
  eng/pipelines/templates/Initialize_Build.yml
  eng/pipelines/templates/Initialize_Build_SemanticVersion.yml
  eng/pipelines/templates/Source_Build.yml
  eng/pipelines/templates/Static_Source_Analysis.yml
  eng/pipelines/templates/Tests_On_Linux.yml
  eng/pipelines/templates/Tests_On_Mac.yml
  scripts/utils/PostGitCommitStatus.ps1
  tools-local/ensure-nupkg-dependencies-on-source/ensure-nupkg-dependencies-on-source.csproj
Labels: Engineering

#6415 Fix 6.8 build, Remove manual GitHub status checks functionality from all pipelines
  eng/pipelines/templates/Apex_Tests_On_Windows.yml
  eng/pipelines/templates/Build_and_UnitTest.yml
  eng/pipelines/templates/CrossFramework_Tests_On_Windows.yml
  eng/pipelines/templates/End_To_End_Tests_On_Windows.yml
  eng/pipelines/templates/Functional_Tests_On_Windows.yml
  eng/pipelines/templates/Initialize_Build.yml
  eng/pipelines/templates/Initialize_Build_SemanticVersion.yml
  eng/pipelines/templates/Source_Build.yml
  eng/pipelines/templates/Static_Source_Analysis.yml
  eng/pipelines/templates/Tests_On_Linux.yml
  eng/pipelines/templates/Tests_On_Mac.yml
  scripts/utils/PostGitCommitStatus.ps1
  tools-local/ensure-nupkg-dependencies-on-source/ensure-nupkg-dependencies-on-source.csproj
Labels: Engineering

#6350 Remove unnecessary CA2022 suppressions
  src/NuGet.Core/NuGet.Packaging/Signing/Archive/SignedPackageArchiveUtility.cs
  src/NuGet.Core/NuGet.ProjectModel/Utf8JsonStreamReader.cs
Labels: Community

#6417 TelemetryOnceEmitter no longer depends on statics, making it more testable and fixing the flaky tests
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Telemetry/TelemetryOnceEmitter.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Telemetry/TelemetryOnceEmitterTests.cs
Labels: Engineering
