Repository NuGet/NuGet.Client, pull requests merged in 2025-05, with the labels that each got.

#6419 Reduce the usage of telemetry statics
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/NuGetProjectManagerService.cs
  src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreManagerPackage.cs
  src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreJob.cs
  src/NuGet.Clients/NuGet.Tools/NuGetBrokeredServiceFactory.cs
  src/NuGet.Clients/NuGet.Tools/NuGetPackage.cs
  src/NuGet.Clients/NuGet.VisualStudio.Common/Telemetry/NuGetPowerShellUsageCollector.cs
  src/NuGet.Clients/NuGet.VisualStudio.Common/Telemetry/NuGetTelemetryProvider.cs
  src/NuGet.Clients/NuGet.VisualStudio.Common/Telemetry/NuGetVSTelemetryService.cs
  src/NuGet.Clients/NuGet.VisualStudio.OnlineEnvironment.Client/NuGetClientPackage.cs
  src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj
  src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/Actions/UIActionEngineTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/UserInterfaceService/NuGetUITests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/CpsPackageReferenceProjectTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Services/NuGetProjectManagerServiceTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Telemetry/ActionsTelemetryServiceTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Telemetry/NavigatedTelemetryEventTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Telemetry/NuGetTelemetryServiceTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Telemetry/RestoreTelemetryServiceTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Telemetry/SearchSelectionTelemetryEventTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Telemetry/TelemetryOnceEmitterTests.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/SolutionRestoreJobTests.cs
  test/NuGet.Core.Tests/NuGet.PackageManagement.Test/NuGetPackageManagerTests/NuGetPackageManagerTelemetryTests.cs
Labels: Engineering

#6374 Promote http warning to error for package commands
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/ListPackage/ListPackageCommandRunner.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageSearch/PackageSearchRunner.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Strings.Designer.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Strings.resx
  src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/HttpSourcesUtility.cs
  src/NuGet.Core/NuGet.Commands/Strings.Designer.cs
  src/NuGet.Core/NuGet.Commands/Strings.resx
  src/NuGet.Core/NuGet.PackageManagement/Strings.Designer.cs
  src/NuGet.Core/NuGet.PackageManagement/Strings.resx
  src/NuGet.Core/NuGet.Protocol/Resources/PackageUpdateResource.cs
  src/NuGet.Core/NuGet.Protocol/Strings.Designer.cs
  src/NuGet.Core/NuGet.Protocol/Strings.resx
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetListPackageTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetPackageSearchTests.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/PackageSearchRunnerTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/Resources/PackageUpdateResourceTests.cs
Labels: Breaking-change

#6436 Add `Versions.props`
  eng/Versions.props
Labels: Community

#6437 Enable xUnit2024, fix violations
  build/test.targets
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetSourcesCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/CpsPackageReferenceProjectTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/ProjectSystems/LegacyPackageReferenceProjectTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Services/PackageVulnerabilityServiceTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/Utility/GetPackageReferenceUtilityTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/PackCommandTests.cs
  test/NuGet.Core.FuncTests/Msbuild.Integration.Test/MsbuildRestoreTaskPackageSourceMappingTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/ContentFilesTests.cs
  test/NuGet.Core.Tests/NuGet.Configuration.Test/ConfigurationDefaultsTests.cs
  test/NuGet.Core.Tests/NuGet.Credentials.Test/SecurePluginCredentialProviderTests.cs
  test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/RemoteDependencyWalkerTests.cs
  test/NuGet.Core.Tests/NuGet.PackageManagement.Test/BuildIntegration/BuildIntegratedRestoreUtilityTests.cs
  test/NuGet.Core.Tests/NuGet.PackageManagement.Test/NuGetPackageManagerTests/BatchedEventTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/Core/comparers/PackageIdentityComparerTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/IncludeFlagTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/LocalPackageListResourceTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/ServiceIndexResourceV3ProviderTests.cs
Labels: Engineering

#6451 Update build logic for VS targets
  build/config.props
Labels: Engineering

#6449 Introduce -productBuild and -sourceBuild switches
  eng/dotnet-build/build.ps1
  eng/dotnet-build/build.sh
Labels: Community

#6457 Fix release builds
  build/config.props
Labels: Engineering

#6458 Default IsPackable to false for MTP test projects
  src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets
Labels: Community

#6473 Project cleanup - remove VSOE from slnf files and update the project overview doc
  NuGet-Src.slnf
  NuGet-UnitTests.slnf
  NuGet-VS.slnf
  docs/project-overview.md
  src/NuGet.Clients/NuGet.VisualStudio.Client/.vsixignore.CI
Labels: Engineering

#6481 Add 6 new test cases for Dotnet List Package integration test
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetListPackageTests.cs
Labels: Engineering

#6484 Update CODEOWNERS
  .github/CODEOWNERS
  .github/policies/prBuddyAssignment.yml
Labels: Engineering
