Repository NuGet/NuGet.Client, pull requests merged in 2025-06, with the labels that each got.

#6360 Raise error when PackageReference has no version
  src/NuGet.Core/NuGet.Commands/RestoreCommand/DependencyGraphResolver.DependencyGraphItem.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs
  src/NuGet.Core/NuGet.Commands/Strings.Designer.cs
  src/NuGet.Core/NuGet.Commands/Strings.resx
  src/NuGet.Core/NuGet.Commands/Utility/SdkAnalysisLevelMinimums.cs
  src/NuGet.Core/NuGet.Common/Errors/NuGetLogCode.cs
  src/NuGet.Core/NuGet.Common/PublicAPI.Unshipped.txt
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetRestoreTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/SdkAnalysisLevelMinimumsTests.cs
  test/TestUtilities/Test.Utility/TestLogger.cs
Labels: Breaking-change, needs-breaking-change-doc-created

#6504 Stop testing against netcoreapp3.1, which is long deprecated (#6498)
  build/common.project.props
  eng/pipelines/pr.yml
  test/NuGet.Core.FuncTests/NuGet.Commands.FuncTest/NuGet.Commands.FuncTest.csproj
  test/NuGet.Core.FuncTests/NuGet.Packaging.FuncTest/NuGet.Packaging.FuncTest.csproj
  test/NuGet.Core.FuncTests/NuGet.Protocol.FuncTest/NuGet.Protocol.FuncTest.csproj
  test/NuGet.Core.Tests/NuGet.Commands.Test/NuGet.Commands.Test.csproj
  test/NuGet.Core.Tests/NuGet.Configuration.Test/NuGet.Configuration.Test.csproj
  test/NuGet.Core.Tests/NuGet.DependencyResolver.Core.Tests/NuGet.DependencyResolver.Core.Tests.csproj
  test/NuGet.Core.Tests/NuGet.Packaging.Test/NuGet.Packaging.Test.csproj
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/NuGet.ProjectModel.Test.csproj
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/NuGet.Protocol.Tests.csproj
  test/NuGet.Core.Tests/NuGet.Resolver.Test/NuGet.Resolver.Test.csproj
  test/TestExtensions/TestablePlugin/TestablePlugin.csproj
  test/TestUtilities/Microsoft.Internal.NuGet.Testing.SignedPackages/Microsoft.Internal.NuGet.Testing.SignedPackages.csproj
  test/TestUtilities/Test.Utility/Test.Utility.csproj
Labels: Engineering

#6516 Add search package with no argument test
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageSearch/PackageSearchArgs.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/PackageSearchRunnerFixture.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/PackageSearchRunnerTests.cs
Labels: Engineering

#6519 Make LockFileLibrary immutable for performance and sanity reasons
  build/Shared/SharedExtensions.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/CompatibilityChecker.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/LockFileBuilder.cs
  src/NuGet.Core/NuGet.Commands/RestoreCommand/OriginalCaseGlobalPackageFolder.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileFormat.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileLibrary.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/Utf8JsonStreamLockFileLibraryConverter.cs
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Shipped.txt
  src/NuGet.Core/NuGet.ProjectModel/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.ProjectModel/Utf8JsonStreamReader.cs
  src/NuGet.Core/NuGet.Protocol/PackagesFolder/LocalPackageFileCache.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/Commands/Why/DependencyGraphFinderTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/RestoreCommandTests/OriginalCaseGlobalPackageFolderTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/LockFileFormatTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/LockFileLibraryTests.cs
Labels: Community
