Repository NuGet/NuGet.Client, pull requests merged in 2025-09, with the labels that each got.

#6720 remove redundant default constructors
  src/NuGet.Core/NuGet.Packaging/Rules/InvalidUndottedFrameworkRule.cs
  src/NuGet.Core/NuGet.Packaging/Signing/Specifications/SigningSpecificationsV1.cs
  src/NuGet.Core/NuGet.Protocol/PackagesFolder/LocalPackageFileCache.cs
  test/NuGet.Core.Tests/NuGet.Credentials.Test/PluginCredentialProviderBuilderTests.cs
  test/NuGet.Core.Tests/NuGet.PackageManagement.Test/BuildIntegratedTests.cs
  test/NuGet.Tests.Apex/NuGet.Console.TestContract/NuGetApexConsoleTestService.cs
  test/NuGet.Tests.Apex/NuGet.PackageManagement.UI.TestContract/NuGetApexUITestService.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex.Daily/NuGetUITestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/Apex/NuGetApexTestService.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NuGetUITestCase.cs
  test/TestUtilities/Test.Utility/PlatformXunitAttributes/CIOnlyFactAttribute.cs
  test/TestUtilities/Test.Utility/PlatformXunitAttributes/CIOnlyTheoryAttribute.cs
  test/TestUtilities/Test.Utility/PlatformXunitAttributes/PackageSourceTheoryAttribute.cs
  test/TestUtilities/Test.Utility/TestServer/TcpListenerServer.cs
Labels: Community

#6760 Disable Mono tests by default (release-6.14.x)
  eng/pipelines/ci.yml
  eng/pipelines/pull_request.yml
Labels: Engineering

#6761 Disable Mono tests by default (release-6.12.x)
  eng/pipelines/ci.yml
  eng/pipelines/pr.yml
  eng/pipelines/pull_request.yml
Labels: Engineering

#6757 Disable Mono tests on PrivateDev by default
  eng/pipelines/ci.yml
  eng/pipelines/pull_request.yml
Labels: Engineering

#6780 Migrate pipelines from Managed Identities to WIF Service Connections
  eng/pipelines/compliance.yml
  eng/pipelines/optprof.yml
  eng/pipelines/templates/Build_and_UnitTest.yml
  eng/pipelines/vs-test/build.yml
Labels: Engineering, Priority:1

#6785 Pin .NET SDK for testing to last working version
  build/DotNetSdkTestVersions.txt
Labels: Engineering

#6716 Avoid the perf hit of using linq .Count()
  .editorconfig
  src/NuGet.Clients/NuGet.CommandLine/Commands/TrustedSignersCommand.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/PackageFeeds/PackageSourceMoniker.cs
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/SearchObject.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/MSBuildAPIUtility.cs
  src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFile.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NetworkCallCountTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetPackCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreMessageTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreTransitiveLoggingTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/Actions/UIActionEngineTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/PackageLicenseUtilitiesTests.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/CpsPackageReferenceProjectTests.cs
  test/NuGet.Clients.Tests/NuGet.Tools.Test/NuGetBrokeredServiceFactoryTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetAddPackageTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetSourcesTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/PackCommandTests.cs
  test/NuGet.Core.FuncTests/NuGet.Packaging.FuncTest/SigningTests/AllowListVerificationProviderTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/AddPackageCommandUtilityTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/DotnetCliUtil.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatAddPkgTests.cs
  test/NuGet.Core.Tests/NuGet.Build.Tasks.Test/GetRestoreSettingTaskTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/IncludeTypeTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/MSBuildRestoreUtilityTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/ProjectResolutionTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/RestoreCommandTests/Utility/AuditUtilityTests.cs
  test/NuGet.Core.Tests/NuGet.Configuration.Test/ConfigurationDefaultsTests.cs
  test/NuGet.Core.Tests/NuGet.Configuration.Test/SettingsTestUtils.cs
  test/NuGet.Core.Tests/NuGet.Configuration.Test/SettingsTests.cs
  test/NuGet.Core.Tests/NuGet.Credentials.Test/PluginCredentialProviderBuilderTests.cs
  test/NuGet.Core.Tests/NuGet.Credentials.Test/SecurePluginCredentialProviderBuilderTests.cs
  test/NuGet.Core.Tests/NuGet.Frameworks.Test/CompatibilityTableTests.cs
  test/NuGet.Core.Tests/NuGet.PackageManagement.Test/NuGetPackageManagerTests/PackageSourceMappingTests.cs
  test/NuGet.Core.Tests/NuGet.PackageManagement.Test/V2V3ParityTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/ContentModelTests/ContentModelBuildTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/ContentModelTests/ContentModelContentFilesTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/ContentModelTests/ContentModelLibTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/InvalidUndottedFrameworkRuleTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/NuSpecCoreReaderTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/NuspecReaderTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/PackageArchiveReaderTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/PackagesConfigWriterTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/SigningTests/SigningUtilityTests.cs
  test/NuGet.Core.Tests/NuGet.ProjectModel.Test/LockFileFormatTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/PackageSearchResourceV3Tests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/PowershellAutoCompleteResourceTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/Utility/MetadataReferenceCacheTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/V2FeedParserTests.cs
  test/NuGet.Core.Tests/NuGet.Resolver.Test/ResolverTests.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/Utility/CommonUtility.cs
  test/TestExtensions/GenerateLicenseList/Program.cs
  test/TestUtilities/Test.Utility/SimpleTestSetup/SimpleTestProjectContext.cs
  test/TestUtilities/Test.Utility/TestPackagesCore.cs
Labels: Merge next release, Community, Status:No recent activity

#6719 Remove un used parameters
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/PushCommandTest.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/RestoreCommandSignPackagesTests.cs
  test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/RestoreCommandTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/FeedPackagePruningTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NetworkCallCountTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetInstallCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetRestoreCommandTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetUpdateCommandTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/ProjectFactoryTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreLoggingTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreMessageTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreTransitiveLoggingTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreUAPPackageReferenceTests.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/Util.cs
  test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/ViewModels/PackageItemViewModelTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetAddPackageTests.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetRestoreTests.cs
  test/NuGet.Core.FuncTests/Msbuild.Integration.Test/GenerateRestoreGraphFileTargetTests.cs
  test/NuGet.Core.FuncTests/Msbuild.Integration.Test/MsbuildRestoreTaskPackageSourceMappingTests.cs
  test/NuGet.Core.FuncTests/Msbuild.Integration.Test/MsbuildRestoreTaskTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/ListPackageTests.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/MSBuildAPIUtilityTests.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/NETCoreRestoreTestUtility.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/NETCoreRestoreTestUtility.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/RestoreBuildTargetsAndPropsTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/TestUtilityTests.cs
  test/NuGet.Core.Tests/NuGet.Packaging.Test/SigningTests/TstInfoTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/ServiceIndexResourceV3ProviderTests.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex.Daily/NetCoreProjectTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex.Daily/NuGetConsoleTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex.Daily/NuGetUITestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/NuGetEndToEndTests/NetCoreProjectTestCase.cs
  test/NuGet.Tests.Apex/NuGet.Tests.Apex/Utility/CommonUtility.cs
  test/TestUtilities/Microsoft.Internal.NuGet.Testing.SignedPackages/Asn1/Accuracy.cs
  test/TestUtilities/Microsoft.Internal.NuGet.Testing.SignedPackages/Asn1/GeneralName.cs
  test/TestUtilities/Microsoft.Internal.NuGet.Testing.SignedPackages/Asn1/TstInfo.cs
  test/TestUtilities/Microsoft.Internal.NuGet.Testing.SignedPackages/SignatureTestUtility.cs
  test/TestUtilities/Test.Utility/Protocol/StaticHttpSource.cs
  test/TestUtilities/Test.Utility/SimpleTestSetup/SimpleTestSolutionContext.cs
  test/TestUtilities/Test.Utility/TestPackageSpecFactory.cs
  test/TestUtilities/Test.Utility/TestPackages.cs
Labels: Merge next release, Community
