Repository NuGet/NuGet.Client, pull requests merged in 2025-01, with the labels that each got.

#6212 Fix formatting in GraphOperations
  src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/GraphOperations.cs
Labels: Community

#6216 Use .NET SDK 9.0.2xx for integration tests
  build/DotNetSdkTestVersions.txt
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetIntegrationTestFixture.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetWhyTests.cs
Labels: Engineering

#6213 Update config.props to 17.14 Preview 1
  build/config.props
Labels: Merge next release

#6226 Disable static analysis in PrivateDev build for release-6.8.x
  eng/pipelines/pull_request.yml
  eng/pipelines/templates/pipeline.yml
Labels: Engineering

#6227 Disable static analysis in PrivateDev build for release-6.10.x
  eng/pipelines/pull_request.yml
  eng/pipelines/templates/pipeline.yml
Labels: Engineering

#6232 Use hosted agents with Visual Studio 2022 17.12 temporarily
  eng/pipelines/pr.yml
Labels: Engineering

#6219 Use new serializer library to parse solution files
  Directory.Packages.props
  NuGet.Config
  eng/SourceBuildPrebuiltBaseline.xml
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/ListPackage/ListPackageCommandRunner.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/Why/WhyCommand.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/Why/WhyCommandArgs.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/Why/WhyCommandRunner.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/NuGet.CommandLine.XPlat.csproj
  src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/MSBuildAPIUtility.cs
  src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/XPlatUtility.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/ListPackageTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatWhyTests.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/Commands/Why/WhyCommandLineParsingTests.cs
  test/NuGet.Core.Tests/NuGet.CommandLine.Xplat.Tests/MSBuildAPIUtilityTests.cs
  test/TestUtilities/Test.Utility/SimpleTestSetup/SimpleTestSolutionContext.cs
Labels: Community

#6233 Use the documented Artifact extension point to add artifacts
  eng/Publishing.props
Labels: Community

#6240 Bump runnables to net9.0
  build/DotNetSdkVersions.txt
  build/common.project.props
  eng/pipelines/pr.yml
  src/NuGet.Core/NuGet.Commands/SignCommand/CertificateProvider.cs
  src/NuGet.Core/NuGet.Commands/SignCommand/SignCommandRunner.cs
  test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs
  test/NuGet.Core.FuncTests/NuGet.Packaging.FuncTest/SigningTests/SigningUtilityTests.cs
  test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatClientCertTests.cs
  test/NuGet.Core.Tests/NuGet.Commands.Test/SignCommandRunnerTests.cs
  test/TestUtilities/Microsoft.Internal.NuGet.Testing.SignedPackages/Asn1/OcspSignature.cs
  test/TestUtilities/Microsoft.Internal.NuGet.Testing.SignedPackages/Asn1/TestSignedCms.cs
Labels: Engineering
