Repository NuGet/NuGet.Client, pull requests merged in 2025-07, with the labels that each got.

#6541 Pin .NET SDK used by Dotnet.Integration.Tests
  build/DotNetSdkTestVersions.txt
  configure.sh
Labels: Engineering

#6554 Fix NuGet->SDK Codeflow
  Directory.Packages.props
  build/DotNetSdkTestVersions.txt
  src/NuGet.Core/NuGet.CommandLine.XPlat/Program.cs
  test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetIntegrationTestFixture.cs
  test/TestUtilities/Test.Utility/TestDotnetCLiUtility.cs
Labels: Community

#6555 Throw exception for HTTP resource endpoints
  src/NuGet.Core/NuGet.Commands/RestoreCommand/SourceRepositoryDependencyProvider.cs
  src/NuGet.Core/NuGet.Protocol/HttpSource/HttpSource.cs
  src/NuGet.Core/NuGet.Protocol/HttpSource/HttpSourceException.cs
  src/NuGet.Core/NuGet.Protocol/Providers/RepositorySignatureResourceProvider.cs
  src/NuGet.Core/NuGet.Protocol/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Protocol/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Protocol/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/NuGet.Core/NuGet.Protocol/Strings.Designer.cs
  src/NuGet.Core/NuGet.Protocol/Strings.resx
  test/NuGet.Core.FuncTests/NuGet.Commands.FuncTest/RestoreCommandTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/HttpSource/HttpSourceTests.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/Providers/RepositorySignatureResourceProviderTests.cs
  test/TestUtilities/Test.Utility/SelfSignedHttpsServerWithHttpResources.cs
Labels: Breaking-change

#6567 Throw an exception for Http search in PackageSearchResourceV3
  src/NuGet.Core/NuGet.Protocol/HttpSource/HttpSource.cs
  test/NuGet.Core.Tests/NuGet.Protocol.Tests/PackageSearchResourceV3Tests.cs
  test/TestUtilities/Test.Utility/ProtocolUtility.cs
Labels: Breaking-change, needs-breaking-change-doc-created

#6571 Make official & Private builds retryable
  eng/pipelines/templates/pipeline.yml
Labels: Engineering

#6576 remove redundant dictionary lookup in RecommenderPackageFeed
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/PackageFeeds/RecommenderPackageFeed.cs
Labels: Community

#6627 remove un-used GetDirectoryName in MisplacedAssemblyOutsideLibRule
  src/NuGet.Core/NuGet.Packaging/Rules/MisplaceAssemblyOutsideLibRule.cs
Labels: Community

#6642 use cast instead of as and null check in CommandLineParser.AssignValue
  src/NuGet.Clients/NuGet.CommandLine/CommandLineParser.cs
Labels: Community

#6624 remove un-used variables in PackageBuilder
  src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs
Labels: Community

#6618 remove LoggerAdapter instance in NuGetPackageManager
  src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs
Labels: Community

#6630 remove un-used identity instance in LocalV3FindPackageByIdResource
  src/NuGet.Core/NuGet.Protocol/LocalRepositories/LocalV3FindPackageByIdResource.cs
Labels: Community

#6636 remove _project* fields from PackageReferenceProject
  src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/PackageReferenceProject.cs
Labels: Community

#6597 fix nullability in PackageModelCreationTestHelper
  test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/Models/Package/PackageModelCreationTestHelper.cs
Labels: Community

#6653 Remove obsolete APIs from VS Solution Restore tests
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/IVsTargetFrameworkInfo3Test.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/ProjectRestoreInfo3Adapter.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/ProjectRestoreInfoBuilder.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/TestProjectRestoreInfoBuilder.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VSNominationUtilitiesTests.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsItemList.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsProjectProperties.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsProjectProperty.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsProjectRestoreInfo.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsProjectRestoreInfo2.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsReferenceItem.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsReferenceItem2.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsReferenceItems.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsReferenceProperties.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsReferenceProperty.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsSolutionRestoreServiceTests.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsTargetFrameworkInfo.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsTargetFrameworkInfo2.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsTargetFrameworkInfo3.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsTargetFrameworkInfo4.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsTargetFrameworks.cs
  test/NuGet.Clients.Tests/NuGet.SolutionRestoreManager.Test/VsTargetFrameworks2.cs
Labels: Engineering

#6664 Remove pre-signtool signtarget deps
  build/common.targets
Labels: Engineering
